recipes = {
    "demo": {
        "description": "Auto generated by feedcooker with love.",
        "urls": [
            # "https://benmccormick.org/feed.json",
            "https://newsletter.banklesshq.com/feed",
            "https://mirror.xyz/0x31d61b448700D321536FF36A2cd299a1dea14CA2/feed/atom",
            "https://vitalik.ca/feed.xml",
        ],
    },
}
