import operator
from functools import reduce

import listparser


_recipes = {
    "Newsletter": {
        "urls": [
            "https://aiweekly.co/issues.rss",
            "http://feeds.feedburner.com/ruanyifeng",
            "http://fex.baidu.com/feed.xml",
            "https://popular.info/feed",
            "https://2d2d.io/feed.xml",
            "https://3blue1brown.substack.com/feed",
            "https://abouttrading.substack.com/feed",
            "https://adplist.substack.com/feed",
            "https://algofin.substack.com/feed",
            "https://alicecamera.substack.com/feed",
            "https://astrojuanlu.substack.com/feed",
            "https://barnabe.substack.com/feed",
            "https://beyonddeeplearning.substack.com/feed",
            "https://bifarinthefifth.substack.com/feed",
            "https://blknoiz06.substack.com/feed",
            "https://blog.artivatic.ai/feed",
            "https://bohutang.substack.com/feed",
            "https://braddelong.substack.com/feed",
            "https://cheminblanc.substack.com/feed",
            "https://chrismessina.substack.com/feed",
            "https://climatetechvc.substack.com/feed",
            "https://cloudedjudgement.substack.com/feed",
            "https://codybrown.substack.com/feed",
            "https://constructionphysics.substack.com/feed",
            "https://creativerly.com/rss/",
            "https://curtismchale.ca/feed",
            "https://dailydropout.substack.com/feed",
            "https://dangrover.substack.com/feed",
            "https://dataelixir.com/feed/",
            "https://datascienceeducation.substack.com/feed",
            "https://datasciencepe.substack.com/feed",
            "https://dbweekly.com/rss",
            "https://deeplearning.substack.com/feed",
            "https://degencode.substack.com/feed",
            "https://digitalnative.substack.com/feed",
            "https://digitaltechweekly.substack.com/feed",
            "https://dspn.substack.com/feed",
            "https://elvissaravia.substack.com/feed",
            "https://email.joinai.la/feed",
            "https://eugenewei.substack.com/feed",
            "https://extendo.substack.com/feed",
            "https://floxuspythonbootcamp.substack.com/feed",
            "https://fradser.substack.com/feed",
            "https://ghacker.substack.com/feed",
            "https://go.libhunt.com/newsletter/feed",
            "https://golangweekly.com/rss",
            "https://gradientflow.substack.com/feed",
            "https://graphs4sci.substack.com/feed",
            "https://griefbacon.substack.com/feed",
            "https://guzey.substack.com/feed",
            "https://helpkartdatascience.substack.com/feed",
            "https://heyadam.substack.com/feed",
            "https://hfcorriez.substack.com/feed",
            "https://hsxg.ghost.io/rss/",
            "https://interconnected.blog/rss/",
            "https://jiayuanthoughts.substack.com/feed",
            "https://jwuphysics.substack.com/feed",
            "https://marketmeditations.io/feed",
            "https://labnotes.org/rss/",
            "https://laddernewsletter.substack.com/feed",
            "https://lightory.substack.com/feed",
            "https://lillianli.substack.com/feed",
            "https://lingxing.substack.com/feed",
            "https://lludo.substack.com/feed",
            "https://matthewbrennan.substack.com/feed",
            "https://mave99a.substack.com/feed",
            "https://mcdao.mirror.xyz/feed/atom",
            "https://microdegree.substack.com/feed",
            "https://mirror.xyz/0xc19be75B8B9152d884987e1B58b3F18A94875396/feed/atom",
            "https://mitelman.engineering/index.xml",
            "https://ml4sci.substack.com/feed",
            "https://mlindia.substack.com/feed",
            "https://mlops.substack.com/feed",
            "https://modernwebdev.substack.com/feed",
            "https://sinocism.com/feed",
            "https://news.dinehq.net/?format=rss",
            "https://newsitems.substack.com/feed",
            "https://newsletter.huangweidong.me/?format=rss",
            "https://newsletter.pragmaticengineer.com/feed",
            "https://newsletter.uxdesign.cc/feed",
            "https://nlpnews.substack.com/feed",
            "https://normschool.substack.com/feed",
            "https://www.numlock.com/feed",
            "https://offnote.substack.com/feed",
            "https://oldjwu.substack.com/feed",
            "https://p2sh.substack.com/feed",
            "https://pengwu.substack.com/feed",
            "https://pivotal.substack.com/feed",
            "https://productmanager.substack.com/feed",
            "https://pyqml.substack.com/feed",
            "https://readland.substack.com/feed",
            "https://read.first1000.co/feed",
            "https://rizime.substack.com/feed",
            "https://rsshub.app/blogs/hedwig/pangliacci",
            "https://rsshub.app/blogs/hedwig/renzholy",
            "https://rsshub.app/blogs/hedwig/se7en",
            "https://rsshub.app/blogs/hedwig/walnut",
            "https://rsshub.app/cyzone/label/%E5%88%9B%E4%B8%9A%E9%82%A6%E5%91%A8%E6%8A%A5",
            "https://rsshub.app/dev.to/top/month",
            "https://rsshub.app/juejin/trending/ai/monthly",
            "https://rsshub.app/juejin/trending/android/monthly",
            "https://rsshub.app/juejin/trending/backend/monthly",
            "https://rsshub.app/juejin/trending/devops/monthly",
            "https://rsshub.app/juejin/trending/ios/monthly",
            "https://rsshub.app/sznews/press",
            "https://rustacean-station.org/podcast.rss",
            "https://sauravmaheshkar.substack.com/feed",
            "https://serverless.email/rss",
            "https://shodu.substack.com/feed",
            "https://sreweekly.com/feed/",
            "https://storyprism.substack.com/feed",
            "https://strrl.dev/index.xml",
            "https://swagtimus.substack.com/feed",
            "https://technically.substack.com/feed",
            "https://thegradientpub.substack.com/feed",
            "https://thesequence.substack.com/feed",
            "https://thesnippet.substack.com/feed",
            "https://this-week-in-rust.org/atom.xml",
            "https://tsa.substack.com/feed",
            "https://unchartedterritories.tomaspueyo.com/feed",
            "https://uniqtech.substack.com/feed",
            "https://us20.campaign-archive.com/feed?u=88eb3ff0c5a479cf74013ef57&id=362b1686a3",
            "https://us6.campaign-archive.com/feed?u=e4582460499f4aadae1a90e2b&id=d2c14f8a94",
            "https://vadymkhodak.substack.com/feed",
            "https://vinvashishta.substack.com/feed",
            "https://vittles.substack.com/feed",
            "https://weekly.love/feed/",
            "https://weekly.monitoring.love/feed.xml",
            "https://weekly.statuscode.com/rss",
            "https://wulujia.substack.com/feed",
            "https://www.deeplearningweekly.com/feed",
            "https://www.garbageday.email/feed",
            "https://www.newcomer.co/feed",
            "https://www.obsidianroundup.org/blog/rss/",
            "https://www.piratewires.com/feed",
            "https://www.platformer.news/feed",
            "https://www.quastor.org/feed",
            "https://www.readaccelerated.com/feed",
            "https://www.thechatner.com/feed",
            "https://www.sumapositiva.com/feed",
            "https://www.thediff.co/feed",
            "https://www.theinsight.org/feed",
            "https://www.thepullrequest.com/feed",
            "https://www.theshortcut.com/feed",
            "https://www.trackawesomelist.com/week/rss.xml",
            "https://www.vantechjournal.com/feed",
            "https://www.workspaces.xyz/feed",
            "https://xiao.do/?format=rss",
            "https://zwischenzug.substack.com/feed",
            "https://blog.bytebytego.com/feed",
        ],
        "filters": [{"in_seconds": 3600 * 7 * 24}],
    },
    "Inactive": {
        "urls": [
            "http://0xced.blogspot.com/feeds/posts/default",
            "https://24says.com/feed",
            "http://2718.us/blog/feed/",
            "http://accidentaltechnologist.com/feed",
            "https://adad184.com/atom.xml",
            "http://adison.logdown.com/posts.atom",
            "https://adit.io/rss.xml",
            "http://adventuresinnewfield.blogspot.com/feeds/posts/default",
            "https://airspeedvelocity.net/feed",
            "https://alexking.org/blog/feed",
            "https://alisoftware.github.io/feed.xml",
            "http://aniggler.tumblr.com/rss",
            "http://ankit.im/feed.xml",
            "http://articles.morganallanknutson.com/feed",
            "http://www.atalasii.com/rss",
            "http://austinzheng.com/feed.xml",
            "https://babich.biz/rss/",
            "http://beelearning.cn/feed.xml",
            "http://billwang1990.github.io/atom.xml",
            "http://bjk5.com/rss",
            "http://bklimt.tumblr.com/rss",
            "http://blog.appannie.com/feed",
            "http://blog.atwam.com/atom.xml",
            "https://blog.callmewhy.com/atom.xml",
            "http://blog.cee.moe/feed.xml",
            "http://blog.chrismiles.info/feeds/posts/default",
            "https://blog.cnbluebox.com:443/atom.xml",
            "http://blog.cnrainbird.com/index.php/feed",
            "http://blog.cosimahan.com/atom.xml",
            "http://blog.croath.com/rss",
            "https://blog.csdn.net/Android_Tutor/rss/list",
            "https://blog.csdn.net/ArthurChenJS/rss/list",
            "https://blog.csdn.net/HorkyChen/rss/list",
            "https://blog.csdn.net/Luoshengyang/rss/list",
            "https://blog.csdn.net/afatgoat/rss/list",
            "https://blog.csdn.net/androidsecurity/rss/list",
            "https://blog.csdn.net/annkie/rss/list",
            "https://blog.csdn.net/bl1988530/rss/list",
            "https://blog.csdn.net/bonderwu/rss/list",
            "https://blog.csdn.net/cdl2008sky/rss/list",
            "https://blog.csdn.net/ch_soft/rss/list",
            "https://blog.csdn.net/chengyun_chu/rss/list",
            "https://blog.csdn.net/chyroger/rss/list",
            "https://blog.csdn.net/cnsword/rss/list",
            "https://blog.csdn.net/cuibo1123/rss/list",
            "https://blog.csdn.net/dadalan/rss/list",
            "https://blog.csdn.net/delphi090902/rss/list",
            "https://blog.csdn.net/dfgjava/rss/list",
            "https://blog.csdn.net/dongfengsun/rss/list",
            "https://blog.csdn.net/dqjyong/rss/list",
            "https://blog.csdn.net/fengye245/rss/list",
            "https://blog.csdn.net/freexploit/rss/list",
            "https://blog.csdn.net/g9yuayon/rss/list",
            "https://blog.csdn.net/hitwhylz/rss/list",
            "https://blog.csdn.net/iamlazybone/rss/list",
            "https://blog.csdn.net/jasonblog/rss/list",
            "https://blog.csdn.net/java2000_net/rss/list",
            "https://blog.csdn.net/jiahui524/rss/list",
            "https://blog.csdn.net/ju136/rss/list",
            "https://blog.csdn.net/kesalin/rss/list",
            "https://blog.csdn.net/lanphaday/rss/list",
            "https://blog.csdn.net/leonpengweicn/rss/list",
            "https://blog.csdn.net/liangneo/rss/list",
            "https://blog.csdn.net/likendsl/rss/list",
            "https://blog.csdn.net/maojudong/rss/list",
            "https://blog.csdn.net/milado_nju/rss/list",
            "https://blog.csdn.net/muxiqingyang/rss/list",
            "https://blog.csdn.net/nash_/rss/list",
            "https://blog.csdn.net/pjk1129/rss/list",
            "https://blog.csdn.net/terryyhl/rss/list",
            "https://blog.csdn.net/totogo2010/rss/list",
            "https://blog.csdn.net/turingbook/rss/list",
            "https://blog.csdn.net/vagrxie/rss/list",
            "https://blog.csdn.net/visualcatsharp/rss/list",
            "https://blog.csdn.net/volcan1987/rss/list",
            "https://blog.csdn.net/wangkuifeng0118/rss/list",
            "https://blog.csdn.net/wangyuchun_799/rss/list",
            "https://blog.csdn.net/warrenwyf/rss/list",
            "https://blog.csdn.net/wdaming1986/rss/list",
            "https://blog.csdn.net/wzzvictory/rss/list",
            "https://blog.csdn.net/xunyn/rss/list",
            "https://blog.csdn.net/ydfok/rss/list",
            "https://blog.csdn.net/zhangjie201412/rss/list",
            "https://blog.csdn.net/zhangxiaoxiang/rss/list",
            "https://blog.csdn.net/zhao_yin/rss/list",
            "http://blog.databigbang.com/feed/",
            "https://blog.dornea.nu/feeds/atom.xml",
            "http://blog.farmostwood.net/feed",
            "http://blog.google.org/feeds/posts/default",
            "http://blog.ibireme.com/feed",
            "http://blog.iphone-dev.org/rss",
            "https://blog.labix.org/feed",
            "http://blog.liuw.name/feeds/all.rss.xml",
            "http://blog.mikeswanson.com/rss",
            "http://blog.mplayerx.org/atom.xml",
            "https://blog.nektra.com/main/feed",
            "http://blog.palominolabs.com/feed",
            "http://seg.phault.net/blog/index.xml",
            "http://blog.pkh.me/rss.xml",
            "https://blog.pluskid.org/?feed=rss2",
            "http://zyan.cc/feed.php",
            "http://blog.sgmansfield.com/index.xml",
            "http://blog.shpakovski.com/feeds/posts/default",
            "http://blog.sina.com.cn/rss/1050228285.xml",
            "http://blog.sina.com.cn/rss/1136983215.xml",
            "http://blog.sina.com.cn/rss/1223178222.xml",
            "http://blog.sina.com.cn/rss/1271321892.xml",
            "http://blog.sina.com.cn/rss/1279691687.xml",
            "http://blog.sina.com.cn/rss/1307215290.xml",
            "http://blog.sina.com.cn/rss/1309876577.xml",
            "http://blog.sina.com.cn/rss/1494768740.xml",
            "http://blog.sina.com.cn/rss/1569777711.xml",
            "http://blog.sina.com.cn/rss/1608404610.xml",
            "http://blog.sina.com.cn/rss/1609250881.xml",
            "http://blog.sina.com.cn/rss/1664227735.xml",
            "http://blog.sina.com.cn/rss/2015038597.xml",
            "http://blog.sina.com.cn/rss/2246379231.xml",
            "http://blog.sina.com.cn/rss/2536943485.xml",
            "http://blog.sina.com.cn/rss/2684369981.xml",
            "http://blog.sina.com.cn/rss/2706472990.xml",
            "http://blog.sina.com.cn/rss/45543997.xml",
            "http://blog.sina.com.cn/rss/TED.xml",
            "http://blog.sina.com.cn/rss/anxiangnese.xml",
            "http://blog.sina.com.cn/rss/cocoloveqtip.xml",
            "http://blog.sina.com.cn/rss/demidov.xml",
            "http://blog.sina.com.cn/rss/fnlq.xml",
            "http://blog.sina.com.cn/rss/gamestvbbc.xml",
            "http://blog.sina.com.cn/rss/hu_ge.xml",
            "http://blog.sina.com.cn/rss/learningpower.xml",
            "http://blog.sina.com.cn/rss/leijun.xml",
            "http://blog.sina.com.cn/rss/lichengyuan123.xml",
            "http://blog.sina.com.cn/rss/lixiaofeng.xml",
            "http://blog.sina.com.cn/rss/luoxian1984.xml",
            "http://blog.sina.com.cn/rss/matianfu.xml",
            "http://blog.sina.com.cn/rss/raochen000.xml",
            "http://blog.sina.com.cn/rss/rensilu.xml",
            "http://blog.sina.com.cn/rss/shaneyang.xml",
            "http://blog.sina.com.cn/rss/shuo77shuo.xml",
            "http://blog.sina.com.cn/rss/sktelecom.xml",
            "http://blog.sina.com.cn/rss/skypiggs.xml",
            "http://blog.sina.com.cn/rss/tangyan.xml",
            "http://blog.sina.com.cn/rss/twhsi.xml",
            "http://blog.sina.com.cn/rss/xukaicisco.xml",
            "http://blog.solrex.org/feed",
            "http://blog.sourcing.io/feed",
            "http://blog.spinytech.com/atom.xml",
            "http://blog.suchasplus.com/atom.xml",
            "http://blog.sunnyxx.com/atom.xml",
            "http://blog.supertop.co/rss",
            "http://blog.tomtung.com/feed/atom.xml",
            "https://blog.wakoopa.com/feed",
            "http://blog.wangjunyu.net/feed",
            "http://blog.webrtc.is/feed/",
            "http://blog.wilshipley.com/rss.xml",
            "https://blog.wuxinan.net/feed",
            "https://wysaid.org/feed",
            "http://blog.yangmeyer.de/feed.xml",
            "http://blog.yegle.net/feeds/all.atom.xml",
            "http://blog.zhaojie.me/rss",
            "http://blog.zhuoqun.net/atom.xml",
            "http://blogoscoped.com/rss.xml",
            "http://blogs.securiteam.com/index.php/archives/category/commentary/feed",
            "https://bopjiang.github.io/feed.xml",
            "http://borkware.com/miniblog/rss/rss.xml",
            "https://box2d.org/feed",
            "http://brian-webster.tumblr.com/rss",
            "https://bryce.is/writing/code/feed.xml",
            "http://c.gzl.name/feed",
            "http://carloslol.lofter.com/rss",
            "https://casatwy.com/feeds/all.atom.xml",
            "http://cenalulu.github.io/atom.xml",
            "http://cheng.guru/atom.xml",
            "http://chloe1229.lofter.com/rss",
            "http://chrismiles.info/newsbruiser/rss.cgi/cmweblog",
            "http://cnlox.is-programmer.com/posts.rss",
            "http://cocoa.venj.me/atom.xml",
            "http://cocoaheads.tumblr.com/rss",
            "http://cocoamanifest.net/feeds/index.xml",
            "https://cocoasamurai.blogspot.com/feeds/posts/default",
            "https://cocos2dpodcast.wordpress.com/feed",
            "http://codeblog.shape.dk/atom.xml",
            "http://codeseekah.com/feed/",
            "http://codesheriff.blogspot.com/feeds/posts/default",
            "http://cofyc.blogspot.com/feeds/posts/default",
            "http://commandshift.co.uk/atom.xml",
            "http://confusatory.org/rss",
            "http://conradstoll.com/blog?format=RSS",
            "https://corporationunknown.com/blog/feed",
            "https://corte.si/rss.xml",
            "http://creativealgorithms.com/blog/rss.xml",
            "http://cuitianyi.com/feed",
            "http://curtclifton.net/feed.xml",
            "http://daltoncaldwell.com/feed",
            "https://dandreamsofcoding.com/feed",
            "http://dangrover.com/feed.xml",
            "https://darkblue.sdf.org/rss-feed",
            "https://darkdust.net/rss.xml",
            "https://daveabrahams.com/feed",
            "http://davedelong.tumblr.com/rss",
            "http://dbachrach.com/posts/atom.xml",
            "https://ddeville.me/feed.xml",
            "http://devetc.org/feed.xml",
            "http://devmag.org.za/feed/",
            "https://devopsengineer.wordpress.com/feed",
            "http://devopsreactions.tumblr.com/rss",
            "http://diaorui.net/feed",
            "http://digdog.tumblr.com/rss",
            "http://digitalleaves.com/blog/feed",
            "http://dimitrik.free.fr/blog/rss.xml",
            "https://www.ditsing.com/atom.xml",
            "http://doing-it-wrong.mikeweller.com/feeds/posts/default",
            "http://dongxicheng.org/feed",
            "https://donmelton.com/rss.xml",
            "http://dtrace.org/blogs/brendan/feed/",
            "https://easwy.com/blog/feed",
            "http://engineering.postmates.com/feed.xml",
            "http://eric-blue.com/feed/",
            "http://esoftmobile.com/atom.xml",
            "https://ewencp.org/blog/feed.xml",
            "http://fancypixel.github.io/atom.xml",
            "http://feed.cnblogs.com/blog/u/108312/rss",
            "http://feed.feedsky.com/fengyiyi",
            "http://feed.huaidan.org",
            "http://feed.keso.cn/PlayinWithIt",
            "http://feed.netputer.me",
            "http://feed.read.org.cn",
            "https://feedpress.me/chrisyipw",
            "http://feeds.feedburner.com/abinlee-tech",
            "http://feeds.feedburner.com/ArkadiuszHolko",
            "http://feeds.feedburner.com/ChrisEidhof",
            "http://feeds.feedburner.com/Dev2ops",
            "http://feeds.feedburner.com/EnglishAsASecondLanguagePodcast",
            "http://feeds.feedburner.com/IdenticalCousins",
            "http://feeds.feedburner.com/IndieAmbitions",
            "http://feeds.feedburner.com/IphoneDeveloperTips",
            "http://feeds.feedburner.com/IvanJovanovic",
            "http://feeds.feedburner.com/JamesYu",
            "http://feeds.feedburner.com/NatiShalom",
            "http://feeds.feedburner.com/OwenOu",
            "http://feeds.feedburner.com/TechnoWeenie",
            "http://feeds.feedburner.com/TheCodeDump",
            "http://feeds.feedburner.com/ThinkQuarterly",
            "http://feeds.feedburner.com/brandontreb",
            "http://feeds.feedburner.com/ch-linghu",
            "http://feeds.feedburner.com/dailyjs",
            "http://feeds.feedburner.com/dimzzy",
            "http://feeds.feedburner.com/dotnil",
            "http://feeds.feedburner.com/ficklebits",
            "http://feeds.feedburner.com/gSpy",
            "http://feeds.feedburner.com/hacker-news-feed-200?format=xml",
            "http://feeds.feedburner.com/hc1983",
            "http://feeds.feedburner.com/idev101",
            "http://feeds.feedburner.com/iosdevblog",
            "http://feeds.feedburner.com/iospirations",
            "http://feeds.feedburner.com/jazzychadblog",
            "http://feeds.feedburner.com/laoyang945",
            "http://feeds.feedburner.com/nosql",
            "http://feeds.feedburner.com/opensoul",
            "http://feeds.feedburner.com/pongba",
            "http://feeds.feedburner.com/qixinglu",
            "http://feeds.feedburner.com/rcrowley",
            "http://feeds.feedburner.com/realazy",
            "http://feeds.feedburner.com/rmsblog",
            "http://feeds.feedburner.com/rocry",
            "http://feeds.feedburner.com/stuartkhall",
            "http://feeds.feedburner.com/teohm",
            "http://feeds.feedburner.com/timecode",
            "http://feeds.feedburner.com/willerce",
            "http://feeds.feedburner.com/xujiwei",
            "http://feeds.feedburner.com/yannickloriot",
            "http://feeds.feedburner.com/yinhm",
            "http://feeds.tempobook.com/tempobook",
            "http://feeds2.feedburner.com/CasparAnt",
            "http://feeds2.feedburner.com/RickyTestingBlog",
            "http://feeds2.feedburner.com/huojublog",
            "http://feeds2.feedburner.com/lifewithbugs",
            "http://feeds2.feedburner.com/mmdays",
            "http://feeds2.feedburner.com/rexzhao",
            "http://feeds2.feedburner.com/w3er",
            "http://feeds2.feedburner.com/xhacker",
            "http://flexmonkey.blogspot.com/feeds/posts/default",
            "https://flyingmeat.com/blog/atom.xml",
            "http://public-api.wordpress.com/wls/redirect.php?alias=foreverlove2014&feed=rss",
            "http://funwithobjc.tumblr.com/rss",
            "http://gamedusa.blogspot.com/feeds/posts/default",
            "http://ggarlic.org/feed.xml",
            "http://ghosertblog.github.io/atom.xml",
            "http://googleappengine.blogspot.com/atom.xml",
            "http://googleappengine.blogspot.com/feeds/posts/default",
            "http://googleenterprisesuperstars.blogspot.com/feeds/posts/default",
            "http://googlefinanceblog.blogspot.com/atom.xml",
            "http://googlemac.blogspot.com/feeds/posts/default",
            "http://googlemobile.blogspot.com/feeds/posts/default",
            "http://googlephotos.blogspot.com/atom.xml",
            "http://googlephotos.blogspot.com/feeds/posts/default",
            "http://googleproductideas.blogspot.com/feeds/posts/default",
            "http://googlereader.blogspot.com/feeds/posts/default",
            "http://googletalk.blogspot.com/feeds/posts/default",
            "http://googlevideo.blogspot.com/feeds/posts/default",
            "https://grapeot.me/syndication.axd",
            "https://gregheo.com/feed.xml",
            "https://gusc.lv/feed",
            "http://guti.in/feed.xml",
            "http://hackoftheday.securitytube.net/feeds/posts/default",
            "https://halmueller.wordpress.com/feed",
            "https://hamberg.no/erlend/rss.xml",
            "http://haohaoxuexi.iteye.com/rss",
            "https://highlyscalable.wordpress.com/feed",
            "https://honzadvorsky.com/feed.xml",
            "https://huacnlee.com/blog/rss",
            "https://huazong.blog.caixin.com/feed",
            "http://www.hukai.me",
            "https://hunch.net/?feed=rss2",
            "http://hutuworm.blogspot.com/feeds/posts/default",
            "https://icodeit.org/atom.xml",
            "https://ijoshsmith.com/feed",
            "http://ia.net/feed",
            "http://inspired-ui.com/rss",
            "http://invasivecode.tumblr.com/rss",
            "http://iosdevtips.co/rssfeed",
            "https://iosguy.com/feed",
            "http://ipacinoson.blogspot.com/feeds/posts/default",
            "https://itunes.apple.com/cn/rss/customerreviews/id=552718710/sortBy=mostRecent/xml?l=en",
            "https://javascriptweblog.wordpress.com/feed",
            "http://www.jingyuan.info/rss.xml",
            "https://www.templatemonster.com/",
            "http://joris.kluivers.nl/atom.xml",
            "http://journal.stuffwithstuff.com/atom.xml",
            "http://jury.me/blog?format=rss",
            "https://justinas.org/feeds/all.atom.xml",
            "https://kamranahmed.info/atom.xml",
            "https://kanoha.org/feed",
            "http://kickingbear.com/blog/feed",
            "http://kimleo.lofter.com/rss",
            "http://kittenyang.com/rss",
            "http://kostiakoval.github.io/feed.xml",
            "https://krakendev.io/blog?format=RSS",
            "http://ksmx.me/atom.xml/",
            "http://kra.lc/blog/feed",
            "http://kurrytran.blogspot.com/feeds/posts/default",
            "https://lefteyefocus.wordpress.com/feed",
            "https://lifesinger.wordpress.com/feed",
            "http://liovch.blogspot.com.au/feeds/posts/default",
            "http://liruqi.info/rss",
            "http://littlebigdetails.com/rss",
            "http://liuxiang.logdown.com/posts.atom",
            "http://liyong03.github.io/atom.xml",
            "http://localhost-8080.com/feed/",
            "https://longtimenoc.com/feed",
            "http://luikore.github.io/atom.xml",
            "http://lumiwu.com/atom.xml",
            "http://luy.li/feed",
            "http://madeforios7.tumblr.com/rss",
            "http://maitian.blog.techweb.com.cn/rss2.xml",
            "http://www.makingmoneywithandroid.com/feed/",
            "https://maniacdev.com/feed",
            "http://marcio.io/index.xml",
            "http://marginalfutility.net/atom.xml",
            "http://mathewsanders.com/feed.xml",
            "https://matt.might.net/articles/feed.rss",
            "http://mattsnider.com/feed/",
            "https://mechanical-sympathy.blogspot.com/feeds/posts/default",
            "https://meditic.com/feed",
            "http://mentalfaculty.tumblr.com/rss",
            "http://meyerweb.com/eric/thoughts/rss2/full",
            "http://mikeabdullah.net/index.xml",
            "http://mindhacks.cn/feed/",
            "http://modocache.io/feed",
            "http://moonspica.blogspot.com/feeds/posts/default",
            "http://mrgan.tumblr.com/rss",
            "http://mrpeak.cn/feed.xml",
            "http://msching.github.io/atom.xml",
            "http://naituw.github.io/atom.xml",
            "http://nanshu.wang/index.xml",
            "http://natashatherobot.com/feed",
            "http://newgenerationresearcher.blogspot.com/feeds/posts/default",
            "https://nickbradbury.com/feed",
            "http://nilsou.com/atom.xml",
            "https://nlpers.blogspot.com/feeds/posts/default",
            "https://nomothetis.svbtle.com/feed",
            "http://nonamelive.com/?feed=rss2",
            "http://note.leodev.me/atom.xml",
            "http://nscookbook.com/feed",
            "http://nsomar.com/rss",
            "http://obsessedwith.me/feed",
            "http://oncenote.com/feed",
            "http://one37.net/blog?format=rss",
            "http://onstartups.com/rss.xml",
            "https://bigc.at/feed",
            "https://osteele.com/blog/rss.xml",
            "http://overooped.com/rss",
            "https://owensd.io/rss.xml",
            "https://www.paulirish.com/feed",
            "https://pempek.net/feed",
            "http://petersteinberger.com/atom.xml",
            "http://php.js.cn/rss/",
            "http://pieteromvlee.tumblr.com/rss",
            "http://pjgod.iteye.com/rss",
            "https://prakhar.me/index.xml",
            "http://preshing.com/feed",
            "https://priyacheers.wordpress.com/feed",
            "https://prutser.wordpress.com/feed",
            "http://pstgroup.blogspot.com/feeds/posts/default",
            "https://pulkitgoyal.in/rss",
            "http://radex.io/feed.atom",
            "http://rcnote.blogspot.com/feeds/posts/default",
            "https://rdsquared.wordpress.com/feed",
            "http://reality.hk/rss",
            "http://rechargeit.blogspot.com/feeds/posts/default",
            "http://rentzsch.tumblr.com/rss",
            "https://ridiculousfish.com/blog/atom.xml",
            "http://rocry.blogspot.com/feeds/comments/full",
            "http://rocry.blogspot.com/feeds/posts/default",
            "http://rocry.com/feed.xml",
            "http://ronnqvi.st/atom.xml",
            "http://roopc.net/rss.xml",
            "http://rss.bitfoc.us",
            "https://rtorres.me/blog.rss",
            "http://ryanipete.com/blog/feed.xml",
            "http://s1mn.tumblr.com/rss",
            "https://sachagreif.com/feed",
            "http://samvermette.com/.rss",
            "https://scanlime.org/feed",
            "http://seattlexcoders.org/atom.xml",
            "https://setosa.io/blog/feed.xml",
            "http://sevenbits-tech-blog.blogspot.com/feeds/posts/default",
            "http://shawphy.com/feed",
            "https://sheilasweblog.wordpress.com/feed",
            "http://sheinchina.blogspot.com/feeds/posts/default",
            "http://sherlockyao.com/atom.xml",
            "https://stackoverflow.com/feeds/tag?tagnames=android&sort=votes",
            "https://stevenpsmith.wordpress.com/feed",
            "http://stmts.net/feed/",
            "http://stu.mp/feed",
            "http://studentdeng.github.io/atom.xml",
            "http://subjc.com/atom.xml",
            "http://swaggadocio.com/rss",
            "http://swift.emilie.ninja/rss",
            "http://swiftc.io/rss",
            "http://tanqisen.github.io/atom.xml",
            "http://tasuka.idv.tw/blog/rss.php",
            "http://tech.t9i.in/feed/",
            "http://terribleswiftideas.tumblr.com/rss",
            "http://theiostimes.com/feed.xml",
            "http://themacro.com/feed.xml",
            "http://therecord.co/xml/rss.xml",
            "https://thoughtinfection.wordpress.com/feed",
            "http://torvalds-family.blogspot.com/feeds/posts/default",
            "http://public-api.wordpress.com/wls/redirect.php?alias=tsounaiq&feed=rss",
            "https://tzisoftware.com/blog/feed",
            "http://ucdchina.com/rss/all",
            "http://ucdchina.com/rss/category?id=7",
            "https://use-the-index-luke.com/blog/feed",
            "http://vocaro.com/trevor/blog/feed/",
            "http://vombat.tumblr.com/rss",
            "http://walkendstar.tumblr.com/rss",
            "https://readkit.app/blog/rss",
            "http://webinsightlab.com/feed/",
            "https://weblogs.asp.net/yuanjian/rss.aspx",
            "http://weicdsq.lofter.com/rss",
            "http://weilu.github.io/atom.xml",
            "http://witcheryne.iteye.com/rss",
            "http://wonderffee.github.io/atom.xml",
            "http://worrydream.com/feed.xml",
            "http://www.43folders.com/rss.xml",
            "https://www.7dot9.com/feed",
            "https://www.99css.com/rss",
            "https://www.airs.com/blog/feed",
            "http://alexhill.cn/feed/",
            "https://www.appleoutsider.com/feed",
            "https://www.atomicbird.com/feed",
            "https://blendedcocoa.com/atom.xml",
            "http://www.blogjava.net/caipinjob/rss.aspx",
            "http://www.blogjava.net/jayslong/rss.aspx",
            "http://www.blogjava.net/killme2008/rss.aspx",
            "http://www.blogjava.net/oathleo/rss.aspx",
            "http://www.blogjava.net/zh-weir/rss",
            "http://www.brianjcoleman.com/feed/",
            "https://www.chrisg.com/feed",
            "http://www.cimgf.com/feed/",
            "https://www.cnblogs.com/BeyondAnyTime/rss",
            "https://www.cnblogs.com/Kaysin/rss",
            "https://www.cnblogs.com/Wendale-Zhang/rss",
            "https://www.cnblogs.com/YouXianMing/rss",
            "https://www.cnblogs.com/and/rss",
            "https://www.cnblogs.com/andyque/rss",
            "https://www.cnblogs.com/daizhj/rss",
            "https://www.cnblogs.com/descusr/rss",
            "https://www.cnblogs.com/feilonge/rss",
            "https://www.cnblogs.com/flclain/rss",
            "https://www.cnblogs.com/guanhe/rss",
            "https://www.cnblogs.com/liuhao/rss",
            "https://www.cnblogs.com/not-code/rss",
            "https://www.cnblogs.com/rubylouvre/rss.aspx",
            "https://www.cnblogs.com/stan0714/rss",
            "https://www.cnblogs.com/tuncaysanli/rss",
            "https://www.cnblogs.com/uyoug321/rss",
            "https://www.cnblogs.com/windwithlife/rss",
            "https://www.cnblogs.com/xinz/rss",
            "https://www.cnblogs.com/yiyezhai/rss",
            "http://www.cocoanetics.com/category/podcast/feed/",
            "http://www.cowtowncoder.com/blog/rss.xml",
            "http://www.cppblog.com/abilitytao/rss.aspx",
            "http://www.cppblog.com/converse/rss.aspx",
            "http://www.cppblog.com/deercoder/rss.aspx",
            "http://www.cppblog.com/peakflys/rss.aspx",
            "http://www.cppblog.com/shongbee2/rss.aspx",
            "http://www.cppblog.com/vczh/rss.aspx",
            "http://www.csksoft.net/blog/rss.xml",
            "http://www.dbinterest.com/feed",
            "http://www.douban.com/feed/people/1275898/reviews",
            "http://www.durhamtownship.com/index.rdf",
            "http://www.elasticspace.com/feed",
            "https://www.evanmiller.org/news.xml",
            "https://fatal1tyv.com/feed",
            "https://www.fewbutripe.com/feed.xml",
            "http://www.firedragonpzy.com.cn/index.php/feed",
            "http://www.fullstackyang.com/feed/",
            "https://www.galloway.me.uk/atom.xml",
            "http://www.gdcl.co.uk/rss.xml",
            "http://www.getitdownonpaper.com/atom.xml",
            "http://www.grobinson.me/feed",
            "https://www.haidongji.com/feed",
            "http://www.huangtianhui.com/feed",
            "http://icab.de/blog/feed/",
            "http://www.ifun.cc/atom.xml",
            "http://www.iunbug.com/feed",
            "https://flipbooksoftware.net/xml/rss.xml",
            "https://www.jollen.org/blog/atom.xml",
            "http://www.josephspurrier.com/index.xml",
            "https://www.laruence.com/feed",
            "http://liyaos.com/blog/feed",
            "http://www.macalope.com/feed/",
            "http://www.martinbrochhaus.com/feeds/all.atom.xml",
            "http://www.martip.net/blog/feed",
            "http://www.meirendaddy.com/blog/?feed=rss2",
            "https://www.michaelnygard.com/atom.xml",
            "http://www.mikespook.com/feed",
            "http://www.mitchchn.me/feed.xml",
            "http://www.music-video.cn/feed",
            "http://www.neglectedpotential.com/feed/",
            "http://www.norvig.com/rss-feed.xml",
            "http://www.olinone.com/?feed=rss2",
            "http://www.parallellabs.com/feed/",
            "http://www.perkin.org.uk/rss.xml",
            "https://www.pheelicks.com/index.xml",
            "http://www.pjhome.net/feed.asp",
            "https://ponnuki.net/feed/atom",
            "http://www.rhonabwy.com/wp/feed",
            "http://www.scianski.com/feed/",
            "http://www.sealiesoftware.com/blog/rss.xml",
            "https://www.spinics.net/lists/linux-standards/maillist.rdf",
            "https://www.stefankrause.net/wp/?feed=rss2",
            "http://www.takingnotes.co/atom.xml",
            "https://www.tapirgames.com/feed/atom",
            "https://www.thinkandbuild.it/feed",
            "http://www.upbeat.it/atom.xml",
            "https://uraimo.com/atom.xml",
            "https://www.wired.com/wiredenterprise/feed",
            "http://www.xjp.cc/feed",
            "http://www.xs-labs.com/feed/atom.php",
            "http://www.yy42.net/blog/?feed=rss2",
            "http://www2.technologyreview.com/rss/video_rss.aspx",
            "https://xiaoxia.org/feed",
            "http://xiewenwei.github.io/atom.xml",
            "http://xiezhenye.com/feed",
            "http://yansu.org/pages/atom.xml",
            "http://yaronspace.cn/blog/index.php/feed",
            "http://yarshure.blogspot.com/feeds/posts/default",
            "http://yegle.net/feed",
            "https://yllan.org/blog/feed",
            "https://zearfoss.wordpress.com/feed",
            "https://www.zhang.hu/rss",
            "http://zhangbinliu.me/rss/index.xml",
            "https://zhengpei.wordpress.com/feed",
            "http://zixun.github.io/atom.xml",
            "https://zonble.net/feed",
            "https://anders.unix.se/index.xml",
            "https://andrewnaylor.co.uk/atom.xml",
            "https://blog.heptio.com/feed",
            "https://blog.oasisfeng.com/feed.xml",
            "https://blog.tonyseek.com/atom.xml",
            "https://blogs.oracle.com/mysqlinnodb/feed/entries/atom",
            "https://blogs.oracle.com/mysqlinnodb/feed/entries/rss",
            "https://breakwa11.blogspot.com/feeds/posts/default",
            "https://defaultnamehere.tumblr.com/rss",
            "https://developer.apple.com/swift/blog/news.rss",
            "https://exceptionlevelone.blogspot.com/feeds/posts/default",
            "https://feeds.feedburner.com/JohnResig",
            "https://github.com/Ciechan.atom",
            "https://github.com/fpillet/NSLogger/tags.atom",
            "https://github.com/mneorr.atom",
            "https://github.com/stefanoa.atom",
            "https://idndx.com/rss/",
            "https://infrequently.org/feed",
            "https://jbrandhorst.com/index.xml",
            "https://jingxin.me/blog/atom.xml",
            "https://leafduo.com/atom.xml",
            "https://lvwenhan.com/rss.php",
            "https://maryrosecook.com/blog/feed.xml",
            "https://medium.com/feed/@NSomar",
            "https://medium.com/feed/@scomper",
            "https://perfectforwarding.tumblr.com/rss",
            "https://pikeralpha.wordpress.com/feed/",
            "https://qotoqot.com/blog/rss.xml",
            "https://shuhaowu.com/blog/feed/index.xml",
            "https://sites.google.com/a/athaydes.com/renato-athaydes/posts/posts.xml",
            "https://swiftunboxed.com/feed.xml",
            "https://topologyeyewear.github.io/engineering-blog/atom",
            "https://word.bitly.com/rss",
            "https://www.chiphell.com/portal.php?mod=rss&catid=32",
            "https://www.chiphell.com/portal.php?mod=rss&catid=33",
            "https://www.igvita.com/feed",
            "https://www.ryannn.com/feed/atom",
            "https://www.wrbug.com/atom.xml",
            "https://www.yejianye.com/feed.xml",
            "https://yoichitgy.github.io/index.xml",
        ],
        "filters": [{"in_seconds": 3600 * 7 * 24}],
    },
    # "MP - Security": {
    #     "urls": [
    #         "https://wechat2rss.xlab.app/feed/002fe975bae4232ce63c51ef77519d0f1cb646c8.xml",
    #         "https://wechat2rss.xlab.app/feed/0060dbbf4244fc99ca332d9aa76acfe89ba7b415.xml",
    #         "https://wechat2rss.xlab.app/feed/019145f03889dce72141b912d697750e7e00106a.xml",
    #         "https://wechat2rss.xlab.app/feed/01af96b91d0bd5570ab2c3f1237436791fd47d90.xml",
    #         "https://wechat2rss.xlab.app/feed/01cfcd4441ecc8f68af1df0d3669b9233133932a.xml",
    #         "https://wechat2rss.xlab.app/feed/021e3a28dfa435253d1b5610e6678205ea0919b6.xml",
    #         "https://wechat2rss.xlab.app/feed/02330475f466041c89e4db3abdf4ce9b1311a6cb.xml",
    #         "https://wechat2rss.xlab.app/feed/027c7f3b98d9d0f2db84513f0cb94f02e9a8a3d7.xml",
    #         "https://wechat2rss.xlab.app/feed/034265b14906a59ef7cf1fcbd56699b54a696094.xml",
    #         "https://wechat2rss.xlab.app/feed/059ae07ca76f11c6e9f9fad7698ab205b3b039c8.xml",
    #         "https://wechat2rss.xlab.app/feed/05b37f288856a510f293be0ff7ef4dfe212ec7e0.xml",
    #         "https://wechat2rss.xlab.app/feed/0628f5f1764e0d79813846e7706daef229f464a7.xml",
    #         "https://wechat2rss.xlab.app/feed/073cf053abc1ab6a318b246e8f21386e85c53d6a.xml",
    #         "https://wechat2rss.xlab.app/feed/08f314092c056259db01e6c7075d246ac76dc713.xml",
    #         "https://wechat2rss.xlab.app/feed/09d2ae436c3aa6166353d53502096e1a957a808a.xml",
    #         "https://wechat2rss.xlab.app/feed/09fd2a3e5180ee5ee0f787446046e8bc91f47d65.xml",
    #         "https://wechat2rss.xlab.app/feed/0a0fb079fdb28ad7c49e5a6cbd9cf909c9873d86.xml",
    #         "https://wechat2rss.xlab.app/feed/0aca9799e72cc5f479d8a7b9ceda70d7e2193eb1.xml",
    #         "https://wechat2rss.xlab.app/feed/0c01ac36bf3a4f3153d8c568e1255b9e91825688.xml",
    #         "https://wechat2rss.xlab.app/feed/0d50a0309f855d2f0344f69be89d784ba72941ba.xml",
    #         "https://wechat2rss.xlab.app/feed/0db50f315edb5c0af041413fc89e3d4d80a91fdd.xml",
    #         "https://wechat2rss.xlab.app/feed/0dda9f6157d97813067cd3965f772abc35bfdf4c.xml",
    #         "https://wechat2rss.xlab.app/feed/0e026637254d450ae84c59f87d4e4fb4616651ca.xml",
    #         "https://wechat2rss.xlab.app/feed/10f1ba549b70cdb4216f7ade606d30a813305aa1.xml",
    #         "https://wechat2rss.xlab.app/feed/10fdc27bdac746197d79a7632053fee231f37bcd.xml",
    #         "https://wechat2rss.xlab.app/feed/13584cb01e8bf3297943a0dad49e53c6faf20611.xml",
    #         "https://wechat2rss.xlab.app/feed/1559746776b3cf0a4aea8dd4f2979f71108093de.xml",
    #         "https://wechat2rss.xlab.app/feed/158efac9a94e62404af4bc804a6d6dcd55caa44f.xml",
    #         "https://wechat2rss.xlab.app/feed/164eeaeb12a8d95384d8807f41d3572569296029.xml",
    #         "https://wechat2rss.xlab.app/feed/16a4ec12a83a52e1f6e941bce030a4d64ee26c47.xml",
    #         "https://wechat2rss.xlab.app/feed/1800f529b600474a4cd0434c65654c483739e192.xml",
    #         "https://wechat2rss.xlab.app/feed/181cb187893448582b37198afeadd4c4cf0750a9.xml",
    #         "https://wechat2rss.xlab.app/feed/1861774bb3091197d2b5b99ea778ced110751b8e.xml",
    #         "https://wechat2rss.xlab.app/feed/18cb4f6ce17f4be6e5062dfb47a6036fe9c36a25.xml",
    #         "https://wechat2rss.xlab.app/feed/19e49fc43c29d227aed74edba9830e7e1c71161e.xml",
    #         "https://wechat2rss.xlab.app/feed/1a525e06c123c345dae49c4992df35964b8c4d53.xml",
    #         "https://wechat2rss.xlab.app/feed/1a5aec98e71c707c8ca092bc2c255b9d4bac477d.xml",
    #         "https://wechat2rss.xlab.app/feed/1aa5b8c8e4fb27ccb905694f7563b5529cd12269.xml",
    #         "https://wechat2rss.xlab.app/feed/1bbe066c89588a1aff71eb8b6a4446c7c422499f.xml",
    #         "https://wechat2rss.xlab.app/feed/1bbf7fc5fac024226f86a1851c682253a7eae63f.xml",
    #         "https://wechat2rss.xlab.app/feed/1c1f6eeede24a34f08ac362de07be36f79a7e986.xml",
    #         "https://wechat2rss.xlab.app/feed/21b0fdc5197bc18c5d0a0c4a5a557a98ae4c01c7.xml",
    #         "https://wechat2rss.xlab.app/feed/21b46d78e363b85d6927970267ecea4904f06bc8.xml",
    #         "https://wechat2rss.xlab.app/feed/21f7777ea1da950d1a49edffa59ef75ddbed8684.xml",
    #         "https://wechat2rss.xlab.app/feed/238759eb3e9d042d4e1ef515cfc3686c977c6ddd.xml",
    #         "https://wechat2rss.xlab.app/feed/255746ce1fb5befc63e2be00eb25795409048fcb.xml",
    #         "https://wechat2rss.xlab.app/feed/257bba53d8f6b6485ac41c0f8cd6fdb0f52840b5.xml",
    #         "https://wechat2rss.xlab.app/feed/267f1258101e978e4cc8507724579217adf600cf.xml",
    #         "https://wechat2rss.xlab.app/feed/273e7f746e228d3686d6f2fa59a0df5ef906dd23.xml",
    #         "https://wechat2rss.xlab.app/feed/27be924bf0d49a8d3ff45c0a85e9c6e94ba7a93c.xml",
    #         "https://wechat2rss.xlab.app/feed/280cc6aaef116a9701025a97aa73f7ee731bac36.xml",
    #         "https://wechat2rss.xlab.app/feed/294bc034c9941529cd86a8a4b8999d100186c04d.xml",
    #         "https://wechat2rss.xlab.app/feed/2b0b4d99312e57d27a294d18de8dfb8f9c272fd4.xml",
    #         "https://wechat2rss.xlab.app/feed/2b3d1f9d72a621232894fa96b6ddf218aade7a1f.xml",
    #         "https://wechat2rss.xlab.app/feed/2b4f112d9e25f5ef0abf85e6b31f7d02602672ab.xml",
    #         "https://wechat2rss.xlab.app/feed/2b62c59e45bd71ff9f475c93626cd4871c99f185.xml",
    #         "https://wechat2rss.xlab.app/feed/2d77edf78f6cc321308b81ac9f5d117e2f3fb7d1.xml",
    #         "https://wechat2rss.xlab.app/feed/2dbce2e5f7b49dc8415db7a0ab325929e0f5d8c3.xml",
    #         "https://wechat2rss.xlab.app/feed/2f38aa5ec9e067b1d02196f5a50665f8ec23a4e4.xml",
    #         "https://wechat2rss.xlab.app/feed/3051a5bf0ae50996df7d16a2a9880c021a41d02a.xml",
    #         "https://wechat2rss.xlab.app/feed/308da52e82d7f7bc2a9f6a5f63633c5567b7af08.xml",
    #         "https://wechat2rss.xlab.app/feed/311c02e5c56e5c0bcdf41924909407ed2d569d2a.xml",
    #         "https://wechat2rss.xlab.app/feed/347c1a20a1a8ff2b789e454e938addadc85b2c4b.xml",
    #         "https://wechat2rss.xlab.app/feed/36738a4bf3055c808494d72d9b3372c00f38c8e8.xml",
    #         "https://wechat2rss.xlab.app/feed/373e03599246ef117e24c9ca900acfe168601a81.xml",
    #         "https://wechat2rss.xlab.app/feed/3b20077b01e05fe90c8d62aa2743c36ed8b5165a.xml",
    #         "https://wechat2rss.xlab.app/feed/3b69d8965599130a19b70d7690b5abdb7d107483.xml",
    #         "https://wechat2rss.xlab.app/feed/3bd096819fedf4e94ef23d95c24dd7b2644f3d10.xml",
    #         "https://wechat2rss.xlab.app/feed/3cacd8073bf05a6d23b63613aad68f1c47d846ec.xml",
    #         "https://wechat2rss.xlab.app/feed/3d9ef879f257a0cd3c11fc0b569792ca3581c0b6.xml",
    #         "https://wechat2rss.xlab.app/feed/3fc5f554af76c0164779add7c5206bdc6f2efe5b.xml",
    #         "https://wechat2rss.xlab.app/feed/4025ea55575daf8bfd8227e68b28d9638b073267.xml",
    #         "https://wechat2rss.xlab.app/feed/41a459a80e37e15d9706465eee48ff491911a36f.xml",
    #         "https://wechat2rss.xlab.app/feed/42ae6dc8b414f4be915ce93ae03d8f8460179c72.xml",
    #         "https://wechat2rss.xlab.app/feed/4470030205d4d847065a2f0d26219b280b421440.xml",
    #         "https://wechat2rss.xlab.app/feed/44dc3cfe1a58cd4c818178052cbca34c5f9b336d.xml",
    #         "https://wechat2rss.xlab.app/feed/45ef431eb5e61b3ff7802ef329290a4dcc377031.xml",
    #         "https://wechat2rss.xlab.app/feed/4767e1bec36c42a1c1cf1c991a3a1a027d1b49a5.xml",
    #         "https://wechat2rss.xlab.app/feed/47cf1260cf37d1de55b263afbf47e6cb6cae7d29.xml",
    #         "https://wechat2rss.xlab.app/feed/47ea183e577cf1fc9035122675cc567dec908443.xml",
    #         "https://wechat2rss.xlab.app/feed/48215981e3bd81ce5f1739196cddf14b59835193.xml",
    #         "https://wechat2rss.xlab.app/feed/4b0c13b203b74f4d5b366d98ee2d8420bda258ca.xml",
    #         "https://wechat2rss.xlab.app/feed/4d448e1e341361f81e9dd715b84f4c324053251b.xml",
    #         "https://wechat2rss.xlab.app/feed/4ebcb3d5a0bdb5fada48eb901a77910f8cbef585.xml",
    #         "https://wechat2rss.xlab.app/feed/4ef3bd392bcda3fe411f1a341669e9b0ef946dab.xml",
    #         "https://wechat2rss.xlab.app/feed/4fad165589ac854de97e576a6dbcfbd8b9f75320.xml",
    #         "https://wechat2rss.xlab.app/feed/5086d647f212ae93f39db2da1973dc3f446b0d95.xml",
    #         "https://wechat2rss.xlab.app/feed/544a8a6edc551b8a2975fbb76b7de1637570d0e7.xml",
    #         "https://wechat2rss.xlab.app/feed/54a83613a320eba6bef5bec8e44ecf81b33ed7c3.xml",
    #         "https://wechat2rss.xlab.app/feed/55990eaae05ad1430e2ba4955756b215a99896c9.xml",
    #         "https://wechat2rss.xlab.app/feed/55d7dabccad3e569e3c9fc2a14a07dd86d7b6666.xml",
    #         "https://wechat2rss.xlab.app/feed/567cb1a8cf49f3e2c141d9d8085712f42ffc2fef.xml",
    #         "https://wechat2rss.xlab.app/feed/56ccecd04a64c0459442d07f30325218f8b4f210.xml",
    #         "https://wechat2rss.xlab.app/feed/574587b13c6f60617fc74605702258ddf4aefac6.xml",
    #         "https://wechat2rss.xlab.app/feed/58217cc5c14a568f5b4141527344b58ba7449380.xml",
    #         "https://wechat2rss.xlab.app/feed/5b72c7dcf37ab8e8c6e5745ecf2701b4ba3cd355.xml",
    #         "https://wechat2rss.xlab.app/feed/5b925323244e9737c39285596c53e3a2f4a30774.xml",
    #         "https://wechat2rss.xlab.app/feed/5d5dbfc442f65c9345f4d77cb84e2593d2a0c397.xml",
    #         "https://wechat2rss.xlab.app/feed/60eb4e7d17f9ac498bb307fa863e9fe4cec6fa1d.xml",
    #         "https://wechat2rss.xlab.app/feed/6111a6d5ecf28cfdd4fc9b664244c05ddacef15c.xml",
    #         "https://wechat2rss.xlab.app/feed/61d5b534b36746e49e6b7d52a722968eebe131a7.xml",
    #         "https://wechat2rss.xlab.app/feed/62ba31603ffe26b5a8eca9ddaa434ea612445c10.xml",
    #         "https://wechat2rss.xlab.app/feed/63688861efb2362716368e36b7f8b8b61d0394a9.xml",
    #         "https://wechat2rss.xlab.app/feed/6553a5e852536cc41d797391eb3da8d8f8f3f18d.xml",
    #         "https://wechat2rss.xlab.app/feed/67968324b3147407bc172b38832acd931955e743.xml",
    #         "https://wechat2rss.xlab.app/feed/6ce082e908ac0894ff00b2d9d8e186181cd810bd.xml",
    #         "https://wechat2rss.xlab.app/feed/6e619b6a41994735a9462c567eb402bc1e7ed00b.xml",
    #         "https://wechat2rss.xlab.app/feed/6f07fe5af57e7a13c75b12bd0718840bdf4dc3f2.xml",
    #         "https://wechat2rss.xlab.app/feed/716b21d89522f8bb90b25249ebf00692522d5612.xml",
    #         "https://wechat2rss.xlab.app/feed/71f7fe130360b40edf3b22e222ca2a147912893d.xml",
    #         "https://wechat2rss.xlab.app/feed/7419897e85fdd038ed2f390a5859b730657ec7ff.xml",
    #         "https://wechat2rss.xlab.app/feed/742b34be22c0c323804fa9b541aa717571cd8147.xml",
    #         "https://wechat2rss.xlab.app/feed/74ce3507f54a7a5145a4ddd6e4e3407fd76705b5.xml",
    #         "https://wechat2rss.xlab.app/feed/7528d5257a3331281075aa520209d782adf7bb12.xml",
    #         "https://wechat2rss.xlab.app/feed/773908acbc527a9a8637862bc6fad7fc8a916090.xml",
    #         "https://wechat2rss.xlab.app/feed/7772ec79ac327394596861ae412fc25a823e09d0.xml",
    #         "https://wechat2rss.xlab.app/feed/77cfc87fa0e7200d7ef74c8956eca2e44fd6a4ec.xml",
    #         "https://wechat2rss.xlab.app/feed/7874947663d806190d77bdca6f8f6855f65a1b20.xml",
    #         "https://wechat2rss.xlab.app/feed/7898375f78fd1018302d54577cd0fd05d5ed324f.xml",
    #         "https://wechat2rss.xlab.app/feed/78f3da7a79babd1ab1a2831f37718630f41b77b5.xml",
    #         "https://wechat2rss.xlab.app/feed/792558edf818ce03d377d1d2677afb4d6537853d.xml",
    #         "https://wechat2rss.xlab.app/feed/7a1064e1b9d394f6508a3d4f98475d9f12ce655f.xml",
    #         "https://wechat2rss.xlab.app/feed/7caad9bdb6b168fe174bc815a9b44b7f52d7198b.xml",
    #         "https://wechat2rss.xlab.app/feed/7e9f1ce42f56754f4a6bacb9a67385e48ca643fb.xml",
    #         "https://wechat2rss.xlab.app/feed/7fc9f5344f14228ba49208282d844349f8afdee7.xml",
    #         "https://wechat2rss.xlab.app/feed/8045973546e92ec9048b5cdf10bed4b5889567ea.xml",
    #         "https://wechat2rss.xlab.app/feed/82cb8f76f8e4d0ca29f497944330ef57aa1f22db.xml",
    #         "https://wechat2rss.xlab.app/feed/837190f74457627e0a5567700c573fe8afd7d3fe.xml",
    #         "https://wechat2rss.xlab.app/feed/83f81eece114fa0cb211ab5379fda72760dc5b68.xml",
    #         "https://wechat2rss.xlab.app/feed/84fdb53acad07ab607128a9f387cefdee53809dd.xml",
    #         "https://wechat2rss.xlab.app/feed/85da1127d3027be44cf4f3a7b3198c622f8fbe1b.xml",
    #         "https://wechat2rss.xlab.app/feed/86512202e74d01447788f355c4a4171a3c86740a.xml",
    #         "https://wechat2rss.xlab.app/feed/869b4e387a017fdd76a56b965ee0ab22c2a52dc2.xml",
    #         "https://wechat2rss.xlab.app/feed/8704aa7fd3c472f8c3bbe3c2b553ce9810326202.xml",
    #         "https://wechat2rss.xlab.app/feed/882ec123376dc8e89d3c5f6ef4bd2fdd0af65465.xml",
    #         "https://wechat2rss.xlab.app/feed/88c9f7cfba0f4f60415eedf32cc5958b131c7065.xml",
    #         "https://wechat2rss.xlab.app/feed/88d970d199a87a8a8655e5aa0af7bcea07ac07e6.xml",
    #         "https://wechat2rss.xlab.app/feed/8b57281ce8c62c8bf12743aeb0279bfb807eb00d.xml",
    #         "https://wechat2rss.xlab.app/feed/8c432d74f325c5c6347230d4dc546ecc33c949cd.xml",
    #         "https://wechat2rss.xlab.app/feed/8c5d5f0004e7231abeb01dac49cac5da4ec6933d.xml",
    #         "https://wechat2rss.xlab.app/feed/8c9b7e3366ca88442203715d5616c05d24d0306c.xml",
    #         "https://wechat2rss.xlab.app/feed/8defbaee147ce6fc812f5d1eedca61ea22ecf168.xml",
    #         "https://wechat2rss.xlab.app/feed/90c827b8290310a96ef80a13df9dbcc06ab69892.xml",
    #         "https://wechat2rss.xlab.app/feed/923c0e2f33b6d39c8a826a90f185725f0edb10e8.xml",
    #         "https://wechat2rss.xlab.app/feed/9463336201a9bf776b3820be83260ccc745de53a.xml",
    #         "https://wechat2rss.xlab.app/feed/947b46dba9754e10360d267a5ee9a87597e0bafe.xml",
    #         "https://wechat2rss.xlab.app/feed/956e0bcbfd7dc0ca5274a3489bd2cc03cda26907.xml",
    #         "https://wechat2rss.xlab.app/feed/9685937b45fe9c7a526dbc32e4f24ba879a65b9a.xml",
    #         "https://wechat2rss.xlab.app/feed/9779044929b45805a5c1b0fecf5f6a95c7202818.xml",
    #         "https://wechat2rss.xlab.app/feed/97cd46da8232bd740c02838e1c579182f9636e3e.xml",
    #         "https://wechat2rss.xlab.app/feed/980128c3a0c9ff852a06dd4a2bc3391338e05760.xml",
    #         "https://wechat2rss.xlab.app/feed/981c000a01bbdc1f128d260cc91c15d3a6afb530.xml",
    #         "https://wechat2rss.xlab.app/feed/9823254aff8854917b418bc19efe49ac160669e8.xml",
    #         "https://wechat2rss.xlab.app/feed/9873e439cbe2e1050b8d3a5ee589c12755bda1bb.xml",
    #         "https://wechat2rss.xlab.app/feed/99e8a156f4f0a3b45bb206945e55cb193672da81.xml",
    #         "https://wechat2rss.xlab.app/feed/9b29dedffda96370d7cabfb50c7051efbeaa2554.xml",
    #         "https://wechat2rss.xlab.app/feed/9bce95ccd16c1e5e30f45722847cc9ea2a27c09d.xml",
    #         "https://wechat2rss.xlab.app/feed/9da87fba8130d0c2dc52cc45b844f045227e06a7.xml",
    #         "https://wechat2rss.xlab.app/feed/9e9c3c70e598266a1ac993e50458a10a6d853eb7.xml",
    #         "https://wechat2rss.xlab.app/feed/9ed3866991b2dec386b67cc579ab80f510abccc2.xml",
    #         "https://wechat2rss.xlab.app/feed/9f7e55c77c8eaf5f2adb43289de4fe194f7d34e5.xml",
    #         "https://wechat2rss.xlab.app/feed/a093f5ce01f9dd8377ef4e2554648965b4f5dedd.xml",
    #         "https://wechat2rss.xlab.app/feed/a148ed0a542de4be305ffa1b93e8663ad252e22c.xml",
    #         "https://wechat2rss.xlab.app/feed/a54132c52ec3e562fc896bf803a7fe0aa277bab7.xml",
    #         "https://wechat2rss.xlab.app/feed/a64c88f6f65115735413fa0c7e8be27f6acc8292.xml",
    #         "https://wechat2rss.xlab.app/feed/a884cb33e3393db2f683c48d82012836295ec005.xml",
    #         "https://wechat2rss.xlab.app/feed/a9cfdddef757b0ebac0428f629869b69028c43fa.xml",
    #         "https://wechat2rss.xlab.app/feed/aa202e8b44eec0847ad9ab2bece74addfede9894.xml",
    #         "https://wechat2rss.xlab.app/feed/aa2ff3b0167a3f449f3b116717b5350ab64df8c3.xml",
    #         "https://wechat2rss.xlab.app/feed/ac4004481c5b78892663e13bb3af8422d4ebeb68.xml",
    #         "https://wechat2rss.xlab.app/feed/ac64c385ebcdb17fee8df733eb620a22b979928c.xml",
    #         "https://wechat2rss.xlab.app/feed/ac86a71f04b6d10cc5a87ec9ecc8c94fff5d80d1.xml",
    #         "https://wechat2rss.xlab.app/feed/ad318af292cc4ba7c2466b7a2665b18f760c72ae.xml",
    #         "https://wechat2rss.xlab.app/feed/ae5cf9ab99ae03269527af0f7a6c05ff14d5863c.xml",
    #         "https://wechat2rss.xlab.app/feed/aed7268b7dd5468e8efca43e19948186d7205886.xml",
    #         "https://wechat2rss.xlab.app/feed/aff52b9db3b57b1fcf24b40668d44baecd3da044.xml",
    #         "https://wechat2rss.xlab.app/feed/b12f8ab2025298044029c05a3c26c3bfe8e9256a.xml",
    #         "https://wechat2rss.xlab.app/feed/b2fd128a6c259f160f380ffe90c17ce05bdc780f.xml",
    #         "https://wechat2rss.xlab.app/feed/b43d85353a1b4bdd46153e06264f4b63583a78ae.xml",
    #         "https://wechat2rss.xlab.app/feed/b801577ef970fa6a877911dfd37a7c9ca681d66a.xml",
    #         "https://wechat2rss.xlab.app/feed/b93962f981247c0091dad08df5b7a6864ab888e9.xml",
    #         "https://wechat2rss.xlab.app/feed/bb1aa1ced567490c8eec9d764e4909f694aab711.xml",
    #         "https://wechat2rss.xlab.app/feed/bb354c0b3ebdd4f2a7c27fbbed75eb777943ee42.xml",
    #         "https://wechat2rss.xlab.app/feed/be2795d741304af2370cbf8d31d1e5d3675f8e85.xml",
    #         "https://wechat2rss.xlab.app/feed/bec4267fed1028fa85c18e1281f7a358d6c8c706.xml",
    #         "https://wechat2rss.xlab.app/feed/bf0b754a49db01ae48ef1ab4f912af76eaa9c306.xml",
    #         "https://wechat2rss.xlab.app/feed/c0f0ee37039f7da55ed6ed4ae160d11af1915007.xml",
    #         "https://wechat2rss.xlab.app/feed/c23cb9dcbc234e732381ea10aa3d2fe1394ab36d.xml",
    #         "https://wechat2rss.xlab.app/feed/c396e3a4fb11318adaa9dac2637657d6fe56ba90.xml",
    #         "https://wechat2rss.xlab.app/feed/c6662e88d278561b8293a607dcdcbe26aea98e04.xml",
    #         "https://wechat2rss.xlab.app/feed/c950a13786cac4f432ad2f1dc4ef6dd427a5b802.xml",
    #         "https://wechat2rss.xlab.app/feed/c9f053d41976b087f8df87064a6e1b6223f9cac1.xml",
    #         "https://wechat2rss.xlab.app/feed/ca1fddd8505a3473feed12c0bee898e97d4d5eae.xml",
    #         "https://wechat2rss.xlab.app/feed/ca637daa3c408cbd4eb29972e4449809ed238374.xml",
    #         "https://wechat2rss.xlab.app/feed/ca9e6f3e905e64301c6f00a21f2e3f135df1e691.xml",
    #         "https://wechat2rss.xlab.app/feed/d04e70055c2d31441deb3188d433a027fc8079cc.xml",
    #         "https://wechat2rss.xlab.app/feed/d180634ccb9dccfe000b1cfbb843522811b49172.xml",
    #         "https://wechat2rss.xlab.app/feed/d2b0dc03acc579a8a9c7aa45bf1f531ed5563f59.xml",
    #         "https://wechat2rss.xlab.app/feed/d34c4b291ce2c15655ac1e7d54aa316902ef8968.xml",
    #         "https://wechat2rss.xlab.app/feed/d351be711510e0b7ccbcb275cdfab5c4c7e3e839.xml",
    #         "https://wechat2rss.xlab.app/feed/d568d6fca93d750898111f09cc3c551e7a62f7ab.xml",
    #         "https://wechat2rss.xlab.app/feed/d5a661c1beccdff18ba1ae018514e4d702feac74.xml",
    #         "https://wechat2rss.xlab.app/feed/d5eb8577bf93aacdd7481ad0c3364939096b99a1.xml",
    #         "https://wechat2rss.xlab.app/feed/d762fbf5f8f256afb63bcfe9a362184072338819.xml",
    #         "https://wechat2rss.xlab.app/feed/d93b4641ef7b9ab5bb7a2d41d799544d45ace291.xml",
    #         "https://wechat2rss.xlab.app/feed/dce539f9deadfc68ce8bf82d3be59a4c6d8ddef9.xml",
    #         "https://wechat2rss.xlab.app/feed/de09ec267e5c4545e0a759cc62c3da7866ea49e0.xml",
    #         "https://wechat2rss.xlab.app/feed/e111066ebfbbba805ee4ab5c745b92b5e567bd90.xml",
    #         "https://wechat2rss.xlab.app/feed/e4a8e7ce5182a107ed90452e8738155534dd297a.xml",
    #         "https://wechat2rss.xlab.app/feed/e54af90b7ef21f732ed6d2d7a58d4aefac9f9faa.xml",
    #         "https://wechat2rss.xlab.app/feed/e5a0a3d839536204e4bcec6ede59fe0cc11f6fc6.xml",
    #         "https://wechat2rss.xlab.app/feed/e666c56abbe20a645da315f389ca6247eed264e2.xml",
    #         "https://wechat2rss.xlab.app/feed/e687678d6fc1dacb25e9191fd361250f538e45a1.xml",
    #         "https://wechat2rss.xlab.app/feed/e6da68c95a8f1e2fb40f6691d0ce9addc51a7532.xml",
    #         "https://wechat2rss.xlab.app/feed/e83f8149ea130c384bb4cb8d690b33bd392ce1b6.xml",
    #         "https://wechat2rss.xlab.app/feed/e8caa9248c7b6a8d8d462a4ab3d7ab9181abeefb.xml",
    #         "https://wechat2rss.xlab.app/feed/e91ca0416d5a5dfc93ce14c0598416d4df1a3bf2.xml",
    #         "https://wechat2rss.xlab.app/feed/ea9b226a78afac0166bb9bdee7de836766441073.xml",
    #         "https://wechat2rss.xlab.app/feed/eb4d04149424a874693a51c6fdda0dba8673f5e4.xml",
    #         "https://wechat2rss.xlab.app/feed/edf17c7a01a7152b7a1ca14133258dc4abc1ca61.xml",
    #         "https://wechat2rss.xlab.app/feed/ee4960f396fadae69f69e0711da85f1196e03651.xml",
    #         "https://wechat2rss.xlab.app/feed/f17b52a78a32b532f0d7729e6cf7d94a669c1d53.xml",
    #         "https://wechat2rss.xlab.app/feed/f2035369bae011cc72f020f8ba009ea2dfdf0355.xml",
    #         "https://wechat2rss.xlab.app/feed/f22e132bbbc4e8070cd51c0a84802f940e131a20.xml",
    #         "https://wechat2rss.xlab.app/feed/f27cecd33bae759b29d92450c2c851fba3bc5152.xml",
    #         "https://wechat2rss.xlab.app/feed/f35b2e0c0e9439b0085a851a1514a11c0ad89887.xml",
    #         "https://wechat2rss.xlab.app/feed/f38c9a9f230e19f49918faefc5d0d0fc71e52d29.xml",
    #         "https://wechat2rss.xlab.app/feed/f4087ff02b808a1a995e2ba930219ada5b82425d.xml",
    #         "https://wechat2rss.xlab.app/feed/f4ff9e0e30f68dd38a44232522bdb980791a7587.xml",
    #         "https://wechat2rss.xlab.app/feed/f50063f977eea0ce26836189fb7c3034f7e3d4f8.xml",
    #         "https://wechat2rss.xlab.app/feed/f5af2c80f2132cb0ea9cf4094145ece266a59bc3.xml",
    #         "https://wechat2rss.xlab.app/feed/f70b4cdac52ea7e980b9fa4ab8fbf79a8516f1f3.xml",
    #         "https://wechat2rss.xlab.app/feed/f71ad3ac4c5e75b79b162c720389aa4d8f72bdd3.xml",
    #         "https://wechat2rss.xlab.app/feed/f9a553dbf6aa425ea47b33595b99e612bbcd93ad.xml",
    #         "https://wechat2rss.xlab.app/feed/fa41acf1a0d9c54d4caf973349e7bd99d5de61c6.xml",
    #         "https://wechat2rss.xlab.app/feed/fb1486a83f41d2b3ab5758c9811936beaa762097.xml",
    #         "https://wechat2rss.xlab.app/feed/fc8ebaf92e238784242d7b967d84584a46d1c23d.xml",
    #         "https://wechat2rss.xlab.app/feed/fd912d34201eea9dbaaa73e22bffee21636c0f9e.xml",
    #         "https://wechat2rss.xlab.app/feed/fe0f4b4ed13da1bd9296fe819c5770526ae910b0.xml",
    #         "https://wechat2rss.xlab.app/feed/ffb536c22df3989d8077ce9babb475f41719d62d.xml",
    #     ],
    #     "filters": [{"in_seconds": 3600 * 7 * 24}],
    # },
    "GithuberFeeds": {
        "urls": [
            "https://github.com/CatchZeng.atom",
            "https://github.com/ChristianKienle.atom",
            "https://github.com/DavidCai1993.atom",
            "https://github.com/JaviSoto.atom",
            "https://github.com/KaimingHe.atom",
            "https://github.com/KieranLafferty.atom",
            "https://github.com/Quotation.atom",
            "https://github.com/Rapptz.atom",
            "https://github.com/ayrat555.atom",
            "https://github.com/codegangsta.atom",
            "https://github.com/daimajia.atom",
            "https://github.com/dbsGen.atom",
            "https://github.com/diwu.atom",
            "https://github.com/fastred.atom",
            "https://github.com/gotosleep.atom",
            "https://github.com/grp.atom",
            "https://github.com/h4x3rotab.atom",
            "https://github.com/honcheng.atom",
            "https://github.com/icanzilb.atom",
            "https://github.com/joeldev.atom",
            "https://github.com/jonathanpenn.atom",
            "https://github.com/jspahrsummers.atom",
            "https://github.com/krzysztofzablocki.atom",
            "https://github.com/levey.atom",
            "https://github.com/lldong.atom",
            "https://github.com/m1entus.atom",
            "https://github.com/mattt.atom",
            "https://github.com/mikeash.atom",
            "https://github.com/mpospese.atom",
            "https://github.com/mwaterfall.atom",
            "https://github.com/nicklockwood.atom",
            "https://github.com/norsez.atom",
            "https://github.com/nst.atom",
            "https://github.com/omz.atom",
            "https://github.com/peng-zhihui.atom",
            "https://github.com/qhduan.atom",
            "https://github.com/rentzsch.atom",
            "https://github.com/rnapier.atom",
            "https://github.com/robb.atom",
            "https://github.com/samvermette.atom",
            "https://github.com/stefanoa.atom",
            "https://github.com/theowenyoung.atom",
            "https://github.com/tomlongo.atom",
            "https://github.com/tomusdrw.atom",
            "https://github.com/tonyarnold.atom",
            "https://github.com/tyrchen.atom",
            "https://github.com/xslim.atom",
            "https://github.com/zhongqiangwu960812.atom",
            "https://github.com/bumony.atom",
            "https://github.com/ohdarling.atom",
            "https://github.com/Frix-x.atom",
            "https://github.com/Krupskis.atom",
            "https://github.com/trzy.atom",
            "https://github.com/etown.atom",
            "https://github.com/adamcohenhillel.atom",
            "https://github.com/andelf.atom",
            "https://github.com/HaoboGu.atom",
            "https://github.com/zephray.atom",
            "https://github.com/vroland.atom",
            "https://github.com/septs.atom",
            "https://github.com/mo10.atom",
            "https://github.com/freedom10086.atom",
            "https://github.com/antirez.atom",
            "https://github.com/Schluggi.atom",
            "https://github.com/Plaenkler.atom",
            "https://github.com/sstark.atom",
            "https://github.com/atc1441.atom",
            "https://github.com/nlimper.atom",
            "https://github.com/ihopenot.atom",
            "https://github.com/reece15.atom",
            "https://github.com/skiphansen.atom",
            "https://github.com/XIVN1987.atom",
            "https://github.com/rbaron.atom",
            "https://github.com/devbis.atom",
            "https://github.com/sakumisu.atom",
            "https://github.com/RCSN.atom",
            "https://github.com/github0null.atom",
            "https://github.com/feilongfl.atom",
            "https://github.com/wagiminator.atom",
            "https://github.com/ex3ndr.atom",
        ],
        "filters": [
            {"in_seconds": 3600 * 7 * 24},
            {
                "title": "commented on|closed an issue|opened an issue|merged a pull request|pushed to|deleted branch|created a tag|created a branch",
                "invert": True,
            },
        ],
    },
    "Crypto - Selection": {
        "urls": [
            "https://mirror.xyz/chenboos.eth/feed/atom",
            "https://newsletter.banklesshq.com/feed",
            "https://k.mirror.xyz/feed/atom",
            "https://medium.com/feed/@0xhavel",
            "https://medium.com/feed/@cryptohayes",
            "https://medium.com/feed/@jonas.bostoen",
            "https://mirror.xyz/0x005c0d08AF6B0C4b486916A7bd1F64b6fBaBB8D1/feed/atom",
            "https://mirror.xyz/0x0531c084b7cEd699e7b8908320C752f3F6F49947/feed/atom",
            "https://mirror.xyz/0x0Ec8947fe8685fE1e368e3f729843F41De4A18E6/feed/atom",
            "https://mirror.xyz/0x0F9C6A9d8f9729aB07b5b2B870Ce8122E76708b0/5Ej-S1I5VtQ8EWhRNWH7fFqSyhWWjOAZyGu8Bl9c8aQ/feed/atom",
            "https://mirror.xyz/0x2Bc667d83186CA9F12c9BeFC1C7CBeb9a6DA0677/feed/atom",
            "https://mirror.xyz/0x3D1163E402eC0c0F58297E1e88Bd992b729eE520/feed/atom",
            "https://mirror.xyz/0x410a0887cC91cCf1e8Db56422b9a5D8B078c2200/feed/atom",
            "https://mirror.xyz/0x4631e0eCda7a39ba951f297c65C1A6E680dc94c4/feed/atom",
            "https://mirror.xyz/0x62695C036f5caEf0dbd9BC04e722545Bc7F59eB3/feed/atom",
            "https://mirror.xyz/0x633653A579959D7e2C0331A4d0Ef0D114Fd47aA4/feed/atom",
            "https://mirror.xyz/0x6ACb28b8FF66AbAB7959355697fAaF348099996b/feed/atom",
            "https://mirror.xyz/0x6bd94fB4bEC833C6b666b46D1Bc0e29D14017ad8/feed/atom",
            "https://mirror.xyz/0x81910c6FD8bA1A67367aA9cA30101c61ce1a30e0/feed/atom",
            "https://mirror.xyz/0x8c902B8839010BB1761201d42f788e7eD9FCFD77/feed/atom",
            "https://mirror.xyz/0xAE623c8B158C3dF75b4f0f3886cA36b49b72f3e9/feed/atom",
            "https://mirror.xyz/0xE43a21Ee76b591fe6E479da8a8a388FCfea6F77F/feed/atom",
            "https://mirror.xyz/0xcF372762FE08682528Cba6BfA367A768d7b0afB4/feed/atom",
            "https://mirror.xyz/0xfAd631c21cD293eE714b56198182817ba768B158/feed/atom",
            "https://mirror.xyz/0xsoros.eth/feed/atom",
            "https://mirror.xyz/3344521.eth/feed/atom",
            "https://mirror.xyz/btcdayu.eth/feed/atom",
            "https://mirror.xyz/chessmaster2077.eth/feed/atom",
            "https://mirror.xyz/dao4ever.eth/feed/atom",
            "https://mirror.xyz/foresightnews.eth/feed/atom",
            "https://mirror.xyz/guoyu.eth/feed/atom",
            "https://mirror.xyz/keade.eth/feed/atom",
            "https://mirror.xyz/kirio.eth/feed/atom",
            "https://mirror.xyz/l1ning.eth/feed/atom",
            "https://mirror.xyz/msfew.eth/feed/atom",
            "https://mirror.xyz/nbblockchain.eth/feed/atom",
            "https://mirror.xyz/yueying007.eth/feed/atom",
            "https://mirror.xyz/yufly.eth/feed/atom",
            "https://mirror.xyz/zlexdl.eth/feed/atom",
            "https://shawn.mirror.xyz/feed/atom",
            "https://x.mirror.xyz/feed/atom",
        ],
        "filters": [{"in_seconds": 3600 * 7 * 24}],
    },
    "Jike Topics": {
        "urls": [
            "https://rsshub.app/jike/topic/60484430cc0fe8001152585e",
            "https://rsshub.app/jike/topic/5540e181e4b063749a7abfd9",
            "https://rsshub.app/jike/topic/556688fae4b00c57d9dd46ee",
            "https://rsshub.app/jike/topic/557ed045e4b0a573eb66b751",
            "https://rsshub.app/jike/topic/55b30e4c00b0bb80c43bf532",
            "https://rsshub.app/jike/topic/55e02198dcef9f0e00d7b3c3",
            "https://rsshub.app/jike/topic/5618c159add4471100150637",
            "https://rsshub.app/jike/topic/5635ed20bba31f1100637618",
            "https://rsshub.app/jike/topic/563a2995306dab1300a32227",
            "https://rsshub.app/jike/topic/56972f94a72e39110042406c",
            "https://rsshub.app/jike/topic/5699f451d3e8351200bffdc8",
            "https://rsshub.app/jike/topic/56b78ae36c53a3110026a42d",
            "https://rsshub.app/jike/topic/57079a1526b0ab12002c29da",
            "https://rsshub.app/jike/topic/5738965b6628391200809ff1",
            "https://rsshub.app/jike/topic/577b9a782fa95b1100d9ff2b",
            "https://rsshub.app/jike/topic/577c5a122fa95b1100da059f",
            "https://rsshub.app/jike/topic/58412cc399a0b50010877f8e",
            "https://rsshub.app/jike/topic/597ae4ac096cde0012cf6c06",
            "https://rsshub.app/jike/topic/5a158e62a0ef4f00117ab145",
            "https://rsshub.app/jike/topic/5ab9c9ed2ca389001ba1feb5",
            "https://rsshub.app/jike/topic/5addc0273268d30017822082",
            "https://rsshub.app/jike/topic/5ae18f550974b4001bfdb993",
            "https://rsshub.app/jike/topic/5af18fe3064445001748dcb8",
            "https://rsshub.app/jike/topic/5b1735798e091300174e819c",
            "https://rsshub.app/jike/topic/5b288dde7eea410017e98d20",
        ],
        "filters": [{"in_seconds": 3600 * 7 * 24}],
    },
    "Rust News": {
        "urls": [
            "https://hnrss.org/frontpage.atom?q=rust",
            "https://reddit.com/rust.rss",
        ]
    },
    "Rust Blogs": {
        "urls": [
            "https://blog.mozilla.org/feed/",
            "http://feeds.feedburner.com/steveklabnik/words",
            "http://lucumr.pocoo.org/feed.atom",
            "http://www.jonathanleighton.com/articles.xml",
            "http://feeds.feedburner.com/theifworks",
            "http://smallcultfollowing.com/babysteps/atom.xml",
            "http://brooker.co.za/blog/rss.xml",
            "http://blog.pnkfx.org/atom.xml",
            "https://blog.mozilla.org/nnethercote/feed/",
            "http://seanmonstar.com/rss",
            "http://chrismorgan.info/blog.xml",
            "http://zinc.rs/feed.xml",
            "http://blog.servo.org/feed.xml",
            "https://coaxion.net/blog/feed/",
            "https://brandur.org/articles.atom",
            "https://dirkjan.ochtman.nl/writing/feeds/all.atom.xml",
            "https://blogs.dropbox.com/tech/feed/",
            "http://hermanradtke.com/atom.xml",
            "https://ruudvanasseldonk.com/feed.xml",
            "http://www.chriskrycho.com/feeds/tech.xml",
            "http://blog.madhukaraphatak.com/feed.xml",
            "http://www.randomhacks.net/feed.xml",
            "http://thume.ca/atom.xml",
            "http://feeds.feedburner.com/NikitaBaksalyar",
            "https://hsivonen.fi/feed/atom/",
            "http://pijul.org/feed.xml",
            "http://edunham.net/rss.html",
            "http://www.arewewebyet.org/atom.xml",
            "http://feeds.feedburner.com/jimmycuadra",
            "http://llogiq.github.io/feed.xml",
            "http://www.mattkeeter.com/atom.xml",
            "https://manishearth.github.io/atom.xml",
            "http://www.jonathanturner.org/feed.xml",
            "http://www.suspectsemantics.com/atom.xml",
            "http://xion.io/feeds/atom.xml",
            "http://www.integer32.com/feed.xml",
            "https://jackmott.github.io//feed.xml",
            "http://blog.adamperry.me/feed.xml",
            "https://scribbles.pascalhertleif.de/feed.xml",
            "https://www.platymuus.com/feed.xml",
            "http://fitzgeraldnick.com/feed.xml",
            "http://jamey.thesharps.us/feeds/posts/default",
            "http://pramode.in/feed.xml",
            "http://tesselproject.tumblr.com/rss",
            "https://blog.clap.rs/rss/",
            "http://jamesmunns.com/feed.xml",
            "https://sethcodesthings.blogspot.com/feeds/posts/default",
            "https://aimlesslygoingforward.com/blog/feed.xml",
            "https://gkbrk.com/feed.xml",
            "https://hoverbear.org/feed.xml",
            "http://embed.rs/atom.xml",
            "http://mjtsai.com/blog/2016/10/12/ripgrep/feed/",
            "https://thesquareplanet.com/feed.xml",
            "https://aaboagye.io/feed/",
            "http://disconnected.systems/atom.xml",
            "http://blog.piston.rs/atom.xml",
            "https://lambda.xyz/tags/code.xml",
            "https://cholcombe973.github.io/feed.xml",
            "https://chr4.org/atom.xml",
            "https://kennykerr.ca/feed/",
            "http://blog.jwilm.io/feed.xml",
            "https://gendignoux.com/blog/feed.xml",
            "https://daiheitan.github.io/blog/atom.xml",
            "http://rust.fastmail.com.user.fm/index.xml",
            "http://blog.jeffsmits.net/feed.xml",
            "http://blog.thiago.me/rss/",
            "https://www.ultrasaurus.com/feed/",
            "https://branan.github.io/teensy/feed.xml",
            "http://blog.community.rs/feed.xml",
            "http://relm.ml/atom.xml",
            "http://blog.japaric.io/index.xml",
            "https://jix.one/index.xml",
            "http://bslabs.net/feed.xml",
            "https://perplexinglyemma.blogspot.com/feeds/posts/default",
            "https://simblob.blogspot.com/feeds/posts/default",
            "https://ownyourbits.com/feed/",
            "https://alexeyzabelin.com/feed.xml",
            "https://yoric.github.io/index.xml",
            "https://herald.community.rs/rss",
            "https://raphlinus.github.io/feed.xml",
            "https://samrat.me/feed.xml",
            "https://stainless.io/index.xml",
            "https://routley.io/feed.xml",
            "http://seenaburns.com/feed.xml",
            "https://mnt.io/feed/",
            "https://kadekillary.work/index.xml",
            "https://sywtwaosir.wordpress.com/feed/",
            "https://nical.github.io/feeds/all.atom.xml",
            "https://rcoh.me/index.xml",
            "https://www.janwalter.org/feed.xml",
            "http://rickyhan.com/feed.xml",
            "https://tokio.rs/blog/index.xml",
            "http://aturon.github.io/atom.xml",
            "https://marwes.github.io/feed.xml",
            "https://exyr.org/feed.atom",
            "https://eno.space//blog/feed.xml",
            "https://udoprog.github.io/feed.xml",
            "http://railwayelectronics.blogspot.com/feeds/posts/default",
            "https://libpasta.github.io/index.xml",
            "https://quietmisdreavus.net/feed.xml",
            "https://mgattozzi.com/feed",
            "https://lobste.rs/t/rust.rss",
            "https://thinkof.name/feed.xml",
            "https://epage.github.io/rss.xml",
            "http://casualhacks.net/blog/feed.xml",
            "https://klausi.github.io/rustnish/feed.xml",
            "https://blog.dbrgn.ch/feed.atom",
            "http://mttyng.com/rss.xml",
            "https://fulmicoton.com/atom.xml",
            "http://cityboundsim.com/devblog/rss.xml",
            "http://ithinuel.me/feed.xml",
            "http://www.davideaversa.it/feed/",
            "https://medium.com/feed/tag/rust",
            "https://pagefault.blog/feed/",
            "https://hatsunearu.github.io/feed.xml",
            "https://jneem.github.io/feed.xml",
            "https://sts10.github.io//feed.xml",
            "http://troubles.md/index.xml",
            "https://stevezeidner.com/rss.xml",
            "https://polyfloyd.net/index.xml",
            "https://barrielle.cedeela.fr/research_page/feeds/all.atom.xml",
            "https://dmerej.info/blog/index.xml",
            "https://damad.be/joost/blog/feed.xml",
            "https://theomn.com/rss.xml",
            "http://julio.meroh.net/feed.xml",
            "http://www.bobbin.io/blog/index.xml",
            "https://falseidolfactory.com/feed.xml",
            "https://blog.infinitenegativeutility.com/rss",
            "https://ageof.info/feed.xml",
            "https://iandouglasscott.com/feed.xml",
            "https://blog.shivoa.net/feeds/posts/default",
            "https://pyfisch.org/blog/feed.xml",
            "http://squidarth.com/feed.xml",
            "http://danielwelch.github.io/feeds/all.atom.xml",
            "https://idubrov.github.io/feed.xml",
            "https://bitshifter.github.io/atom.xml",
            "https://blog.burntsushi.net/index.xml",
            "https://robert.ocallahan.org/feeds/posts/default",
            "https://gsquire.github.io/static/index.xml",
            "https://speice.io/feed.xml",
            "https://iqdevs.github.io/feed.xml",
            "https://blog.x5ff.xyz/blog/index.xml",
            "https://www.joshmcguigan.com/rss.xml",
            "https://jamesmunns.com/rss.xml",
            "https://www.ralfj.de/blog/categories/rust.xml",
            "https://mrandri19.github.io/feed.xml",
            "http://timryan.org/feed.xml",
            "http://pcwalton.github.io/feed.xml",
            "https://blog.artemix.org/article/feed",
            "https://benjamincongdon.me/blog/feed.xml",
            "https://philbooth.me/blog.atom",
            "http://alex.amiran.it/rss.xml",
            "https://dorianpula.ca/feed/",
            "https://gibix.github.io/feed.xml",
            "https://thomask.sdf.org/feed.xml",
            "https://hur.st/rss.xml",
            "https://christine.website/blog.rss",
            "http://stevedonovan.github.io/rustifications/feed.xml",
            "https://amanjeev.com/atom.xml",
            "https://lukaskalbertodt.github.io/feed.xml",
            "https://stjepang.github.io/feed.xml",
            "https://blog.anp.lol/feed.xml",
            "https://vorner.github.io/feed.xml",
            "https://leshow.github.io/index.xml",
            "https://blog.ryanlevick.com/index.xml",
            "https://www.cattlegrid.info/feed.xml",
            "https://frehberg.wordpress.com/feed/",
            "https://write.as/balrogboogie/feed/",
            "https://blog.liw.fi/index.rss",
            "https://joshlf.com/index.xml",
            "https://blog.roboinstruct.us/feed.xml",
            "https://boakye.yiadom.org/index.xml",
            "https://varkor.github.io/blog/feed.xml",
            "https://myrrlyn.net/blog.rss",
            "http://blog.ajkavanagh.me/index.xml",
            "https://adelbertc.github.io/feed.xml",
            "https://linuxwit.ch/feed.xml",
            "https://blog.myelin.ch/feed.xml",
            "https://dpc.pw/feed/",
            "http://venshare.com/rss/",
            "https://blog.yoshuawuyts.com/rss.xml",
            "https://spacekookie.de/rss.xml",
            "http://iolivia.me/rss.xml",
            "https://www.cloudatomiclab.com/index.xml",
            "https://estada.ch/feeds/all.atom.xml",
            "https://3plic8.com/feed.xml",
            "https://rushtonality.com/category/languages/rustlang/feed/",
            "https://wayfire.org/feed.xml",
            "https://i.pristi.ga/blog/index.xml",
            "https://natelincoln.com/rss.xml",
            "https://jonathansteyfkens.com/feed.xml",
            "https://veloren.net/rss.xml",
            "https://josh.robsonchase.com/rss.xml",
            "https://nora.codes/index.xml",
            "https://www.forrestthewoods.com/rss.xml",
            "https://randompoison.github.io/feed.xml",
            "https://www.demainilpleut.fr/feed.xml",
            "http://stevenlr.com/index.xml",
            "https://reisub0.gitlab.io/feeds/all.atom.xml",
            "https://kbknapp.dev/rss.xml",
            "https://mcorbin.fr/feed.xml",
            "https://wiredforge.com/rss.xml",
            "https://ljcode.org/rss.xml",
            "https://ehsanmkermani.com/feed/",
            "https://chilimatic.hashnode.dev/rss.xml",
            "https://blog.seantheprogrammer.com/feed",
            "https://feeds.feedburner.com/sebnilsson",
            "https://hagsteel.com/index.xml",
            "https://giordi91.github.io/index.xml",
            "http://camlorn.net/rss.xml",
            "https://beepb00p.xyz/atom.xml",
            "https://fy.blackhats.net.au/blog/html/rss.html",
            "http://kmdouglass.github.io/rss.xml",
            "https://www.jstuber.net/feed.xml",
            "https://bodil.lol/rss.xml",
            "https://oribenshir.github.io/afternoon_rusting/feed.xml",
            "https://kkimdev.github.io/feed.xml",
            "https://zupzup.org/index.xml",
            "https://blog.daveallie.com/rss/",
            "http://blakesmith.me/atom.xml",
            "http://nedellis.com/feed.xml",
            "https://andrzej.pragacz.pl/blog/rss.xml",
            "https://www.mrwade.co.uk/index.xml",
            "https://stephencoakley.com/feed",
            "https://amos.me/index.xml",
            "http://concisecoder.io/feed/",
            "http://antoyo.ml/atom.xml",
            "https://frehberg.com/feed/",
            "https://matklad.github.io/feed.xml",
            "https://interrupt.memfault.com/blog/feed.xml",
            "https://azriel.im/will/index.xml",
            "https://ngoldbaum.github.io/index.xml",
            "http://kvark.github.io/feed.xml",
            "http://cliffle.com/rss.xml",
            "https://gill.net.in/index.xml",
            "https://jonathanklimt.de/feed.xml",
            "https://www.pietroalbini.org/blog/atom.xml",
            "https://blog.eizinger.io/feed.rss",
            "https://www.kerkour.fr/rss.xml",
            "https://caolan.org/posts/rss.xml",
            "https://meli.delivery/rss.xml",
            "https://blog.logrocket.com/feed/",
            "http://iextendable.com/feed/",
            "http://hotforknowledge.com/index.xml",
            "https://blog.paulme.ng/rss/feed.xml",
            "https://rust.graystorm.com/feed/",
            "https://inejge.github.io/blog/rss/",
            "https://svartalf.info/index.xml",
            "https://pauljmiller.com/rss.xml",
            "https://dnlserrano.dev/feed.xml",
            "https://write.as/mokou/feed/",
            "https://tmandry.gitlab.io/blog/index.xml",
            "https://turbomack.github.io/rss.xml",
            "https://tinkering.xyz/rss.xml",
            "https://rfdonnelly.github.io/index.xml",
            "https://www.justanotherdot.com/rss.xml",
            "https://tech.fpcomplete.com/rss.xml",
            "https://averywagar.com/posts/index.xml",
            "https://yaah.dev/feed.xml",
            "https://iximiuz.com/feed.atom",
            "https://mabez.dev/rss.xml",
            "http://osblog.stephenmarz.com/feed.rss",
            "https://wapl.es/feed.xml",
            "https://thomashartmann.dev/rss.xml",
            "http://adventures.michaelfbryan.com/index.xml",
            "https://experimentalworks.net/feed.xml",
            "https://thefullsnack.com/rss.xml",
            "https://www.poor.dev/index.xml",
            "https://tim.mcnamara.nz/rss",
            "https://blog.hwc.io/posts/index.xml",
            "https://apiraino.github.io/feed.xml",
            "https://mmstick.keybase.pub/rss.xml",
            "https://repnop.dev/posts/index.xml",
            "https://haurchefant.fr/rss.xml",
            "https://samsartor.com/rss.xml",
            "https://tomforb.es/index.xml",
            "https://samsieber.tech/posts/index.xml",
            "https://maxdeviant.com/rss.xml",
            "https://blog.eldruin.com/atom.xml",
            "https://bytecodealliance.org/feed.xml",
            "http://www.nushell.sh/blog/feed.xml",
            "https://immunant.com/blog/index.xml",
            "https://hoangpq.github.io/index.xml",
            "https://blaineprice.me/index.xml",
            "https://engineering.redislabs.com/index.xml",
            "https://dev.to/feed/tag/rust",
            "https://sharpend.io/feed.xml",
            "https://www.philipdaniels.com/blog/index.xml",
            "https://blog.nishtahir.com/rss/",
            "https://medium.com/feed/tag/rustlang",
            "https://blog.luizirber.org/feed.xml",
            "https://www.codeslow.com/feeds/posts/default",
            "https://www.vincentprouillet.com/rss.xml",
            "https://www.jakobmeier.ch/feed.xml",
            "https://kooparse.com/rss.xml",
            "https://cprimozic.net/rss.xml",
            "https://leod.github.io/feed.xml",
            "https://relm.antoyo.xyz/feed.xml",
            "https://wduquette.github.io/feed.xml",
            "https://pitdicker.github.io/feed.xml",
            "https://bennetthardwick.com/rss.xml",
            "https://blog.krruzic.xyz/rss.xml",
            "https://phaazon.net/blog/feed",
            "http://blog.levinotik.com/feed/",
            "https://djugei.github.io/rss.xml",
            "https://luciofran.co/blog/index.xml",
            "http://gravitext.com/atom.xml",
            "https://toswak.net/feed.xml",
            "https://kensuenobu.github.io/feed.xml",
            "https://blog.aloni.org/rss.xml",
            "https://cetra3.github.io/rss.xml",
            "https://thaumant.me/rss/",
            "https://blog.hackeriet.no/feed.xml",
            "https://blog.bastion.rs/feed.xml",
            "https://dwarfhack.com/posts/index.xml",
            "https://www.hallada.net/feed.xml",
            "https://belmoussaoui.com/feed/",
            "https://idursun.com/posts/index.xml",
            "https://carette.xyz/index.xml",
            "https://www.fmendez.com/feed.xml",
            "https://materialize.io/rss",
            "https://gal.hagever.com/rss.xml",
            "https://coded.io/index.xml",
            "https://crisal.io/words/feed.xml",
            "https://blog.wnut.pw/feed/",
            "http://yager.io/feed",
            "https://blog.thoughtram.io/rss.xml",
            "https://rolisz.ro/rss/",
            "https://blog.debiania.in.ua/feeds/english.rss",
            "https://www.minimalrust.com/rss.xml",
            "https://avishay.dev/feed.xml",
            "https://blog.turbo.fish/rss.xml",
            "https://treit.github.io/feed.xml",
            "https://xaeroxe.github.io/feed.xml",
            "https://blog.spencerkohan.com/rss/",
            "https://peppe.rs/index.xml",
            "https://rymc.io/rss.xml",
            "https://abramov.io/rss.xml",
            "https://k155la3.blog/posts/index.xml",
            "https://r2.rs/feed/",
            "https://elliehuxtable.com/rss/",
            "https://timidger.github.io/index.xml",
            "https://rustsim.org/blog/atom.xml",
            "https://www.eyalkalderon.com/rss.xml",
            "https://www.voiderror.net/posts/index.xml",
            "https://jpastuszek.net/rss.xml",
            "https://rayoflightz.github.io/feed.xml",
            "https://www.growse.com/feed.xml",
            "https://blue42.net/index.xml",
            "https://nickwilcox.github.io/feed.xml",
            "http://veeenu.github.io/rss",
            "https://www.rubdos.be/feed.xml",
            "https://rodarmor.com/blog/feed.xml",
            "https://gridbugs.org/feed.xml",
            "https://jam1.re/rss",
            "https://blog.yossarian.net/feed.xml",
            "https://www.ruma.io/news/feed.xml",
            "https://fullstackmilk.dev/feed.xml",
            "http://blog.frqc.info/index.xml",
            "https://lowenware.com/blog/index.xml",
            "https://without.boats/index.xml",
            "https://www.halcyon.hr/posts/index.xml",
            "https://blog.kdubovikov.ml/feed.xml",
            "https://steveklabnik.com/atom.rss",
            "https://sachanganesh.com/index.xml",
            "https://gunibert.de/index.xml",
            "https://paytonrules.com/index.xml",
            "https://iamgweej.github.io//feed.xml",
            "http://blog.ielliott.io/feed",
            "https://blog.thomasheartman.com/rss.xml",
            "https://brokenco.de/atom.xml",
            "https://hassamuddin.com/index.xml",
            "https://micouy.github.io/index.xml",
            "https://astonbitecode.github.io/blog/index.xml",
            "https://www.possiblerust.com/feed.xml",
            "https://dystroy.org/blog/atom.xml",
            "https://vasilakisfil.social/blog/feed.xml",
            "https://blog.carlosgaldino.com/atom.xml",
            "http://amitdev.github.io/rss",
            "https://seanchen1991.github.io/index.xml",
            "https://www.taricorp.net/feed.xml",
            "http://www.sheshbabu.com/atom.xml",
            "https://headcrab.rs/feed.xml",
            "https://blog.ael.red/feed.xml",
            "https://benkonz.github.io/feed.xml",
            "https://blog.darrien.dev/posts/index.xml",
            "https://blog.aclysma.com/rss/",
            "https://andres.svbtle.com/feed",
            "https://esimmler.com/rss.xml",
            "https://dygalo.dev/rss.xml",
            "https://killavus.github.io/posts/index.xml",
            "https://onatm.dev/feed.xml",
            "https://www.blog.nodrama.io/feed.xml",
            "https://freyskeyd.fr/index.xml",
            "https://blog.legoktm.com/feeds/all.atom.xml",
            "https://saarw.github.io/feed.xml",
            "https://nickgerace.dev/feed.xml",
            "https://alexene.dev/feed.xml",
            "https://codecrash.me/feed",
            "https://www.abubalay.com/feed.xml",
            "https://www.ecorax.net/rss.xml",
            "https://www.mahmoudashraf.dev/rss.xml",
            "https://ryhl.io/rss.xml",
            "https://tndl.me/rss.xml",
            "https://kobzol.github.io/feed.xml",
            "https://javednissar.ca/rss/",
            "https://pkolaczk.github.io/feed.xml",
            "http://jamesmcm.github.io/atom.xml",
            "https://blog.darrien.dev/index.xml",
            "https://blog.urth.org/feed/",
            "https://www.cmyr.net/feed.xml",
        ],
        "filters": [{"in_seconds": 3600 * 7 * 24}],
    },
    "Keyboard": {
        "urls": [
            "https://geekhack.org/index.php?type=rss;action=.xml;limit=50",
        ],
        "filters": [
            {
                "title": "^Re: ",
                "invert": True,
            },
        ],
    },
}


def get_recipes(prefer_submirror=True) -> [dict]:
    recipes = {}
    for name, recipe in _recipes.items():
        for sub_name, r in _fulfill_opml_recipe(name, recipe).items():
            recipes[sub_name] = r
    if prefer_submirror:
        for recipe in recipes.values():
            _transform_to_submirror(recipe)
    return recipes


def _transform_to_submirror(r: dict):
    for i, u in enumerate(r["urls"]):
        r["urls"][i] = _transform_url_to_submirror(u)


def _transform_url_to_submirror(u: str) -> str:
    from urllib.parse import urlparse

    o = urlparse(u)
    if not o.path.endswith("/feed/atom"):
        return u
    if not o.hostname.endswith("mirror.xyz"):
        return u
    return u.replace("mirror.xyz", "submirror.xyz").rstrip("/feed/atom")


def test_transform_url_to_submirror():
    assert (
        _transform_url_to_submirror(
            "https://mirror.xyz/0xBE4fde70B16d2dD454Fa8434E1A01131b90D2880/feed/atom"
        )
        == "https://submirror.xyz/0xBE4fde70B16d2dD454Fa8434E1A01131b90D2880"
    )
    assert (
        _transform_url_to_submirror("https://dev.mirror.xyz/feed/atom")
        == "https://dev.submirror.xyz"
    )
    assert (
        _transform_url_to_submirror("https://optoutpod.com/blog/feed")
        == "https://optoutpod.com/blog/feed"
    )
    assert (
        _transform_url_to_submirror("https://rocry.com/feed/atom")
        == "https://rocry.com/feed/atom"
    )


# change the recipe with opml url to multi recipes
def _fulfill_opml_recipe(name: str, recipe: dict) -> dict:
    if "opml" not in recipe:
        return {name: recipe}

    result = listparser.parse(recipe["opml"])
    del recipe["opml"]

    feeds = {}
    for f in result.feeds:
        categories = (
            ["uncategorized"]
            if not f.categories
            else reduce(operator.concat, f.categories)
        )
        for c in categories:
            feeds[c] = feeds.get(c, []) + [f.url]

    results = {}
    all_urls = set()
    for key, urls in feeds.items():
        r = recipe.copy()
        r["urls"] = urls
        all_urls.update(urls)
        results[f"{name}_{key}"] = r

    r = recipe.copy()
    r["urls"] = list(all_urls)
    results[name] = r
    return results


if __name__ == "__main__":
    import json

    print(json.dumps(get_recipes()))
