name: Cook Feed

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
# uncomment to run repeatedly
#  schedule:
#    - cron:  '15 * * * *' # every hour at 15 min

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cook-all-feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python main.py --repository="${{ github.repository }}" --repository_owner="${{ github.repository_owner }}"
      - name: Check Git Status
        id: status
        run: '[[ -z $(git status -s) ]] || echo "::set-output name=status::changed"'
      - name: Commit && Push
        if: steps.status.outputs.status == 'changed'
        run: |
          git config --global user.name 'Feed Cooker'
          git config --global user.email 'crysheen+feedcooker@gmail.com'
          git add well-done
          git commit -am "Update feeds"
          git push
