name: Cook Feed

# Controls when the workflow will run
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *' # every hour at 15 min

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cook-all-feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: http-cache
          branch: deploy
          path: downloads
        continue-on-error: true
      - run: python main.py --repository="${{ github.repository }}" --repository_owner="${{ github.repository_owner }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: http-cache
          path: downloads
        continue-on-error: true
      - name: Update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          draft: false
          files: "${{ env.FEEDS_FILES }}"
